// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    id, event, user_id, target_user_id, ip_address, user_agent, request_id, details, success, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_TIMESTAMP
)
`

type InsertAuditLogParams struct {
	ID           string  `json:"id"`
	Event        string  `json:"event"`
	UserID       *string `json:"user_id"`
	TargetUserID *string `json:"target_user_id"`
	IpAddress    *string `json:"ip_address"`
	UserAgent    *string `json:"user_agent"`
	RequestID    *string `json:"request_id"`
	Details      *string `json:"details"`
	Success      bool    `json:"success"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.Event,
		arg.UserID,
		arg.TargetUserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.Details,
		arg.Success,
	)
	return err
}
