// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUpdateHistory = `-- name: CountUpdateHistory :one
SELECT COUNT(*)::int FROM update_history WHERE host_id = $1
`

func (q *Queries) CountUpdateHistory(ctx context.Context, hostID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUpdateHistory, hostID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getDashboardStats = `-- name: GetDashboardStats :one
WITH host_counts AS (
    SELECT
        COUNT(*)::int AS total_hosts,
        COUNT(*) FILTER (WHERE status = 'active' AND last_update < $1)::int AS errored_hosts,
        COUNT(*) FILTER (WHERE status = 'active' AND last_update < $2)::int AS offline_hosts,
        COUNT(*) FILTER (WHERE needs_reboot = true)::int AS hosts_needing_reboot
    FROM hosts
),
hp_package_counts AS (
    SELECT
        COUNT(DISTINCT host_id)::int AS hosts_needing_updates,
        COUNT(DISTINCT package_id)::int AS total_outdated_packages,
        COUNT(DISTINCT package_id) FILTER (WHERE is_security_update)::int AS security_updates
    FROM host_packages
    WHERE needs_update = true
)
SELECT
    hc.total_hosts,
    hpc.hosts_needing_updates,
    hpc.total_outdated_packages,
    hc.errored_hosts,
    hpc.security_updates,
    hc.offline_hosts,
    hc.hosts_needing_reboot,
    (SELECT COUNT(*)::int FROM host_groups),
    (SELECT COUNT(*)::int FROM users),
    (SELECT COUNT(*)::int FROM repositories)
FROM host_counts hc
CROSS JOIN hp_package_counts hpc
`

type GetDashboardStatsParams struct {
	LastUpdate   pgtype.Timestamp `json:"last_update"`
	LastUpdate_2 pgtype.Timestamp `json:"last_update_2"`
}

type GetDashboardStatsRow struct {
	TotalHosts            int32 `json:"total_hosts"`
	HostsNeedingUpdates   int32 `json:"hosts_needing_updates"`
	TotalOutdatedPackages int32 `json:"total_outdated_packages"`
	ErroredHosts          int32 `json:"errored_hosts"`
	SecurityUpdates       int32 `json:"security_updates"`
	OfflineHosts          int32 `json:"offline_hosts"`
	HostsNeedingReboot    int32 `json:"hosts_needing_reboot"`
	Column8               int32 `json:"column_8"`
	Column9               int32 `json:"column_9"`
	Column10              int32 `json:"column_10"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, arg GetDashboardStatsParams) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats, arg.LastUpdate, arg.LastUpdate_2)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalHosts,
		&i.HostsNeedingUpdates,
		&i.TotalOutdatedPackages,
		&i.ErroredHosts,
		&i.SecurityUpdates,
		&i.OfflineHosts,
		&i.HostsNeedingReboot,
		&i.Column8,
		&i.Column9,
		&i.Column10,
	)
	return i, err
}

const getHomepageStats = `-- name: GetHomepageStats :one
WITH active_hosts AS (
    SELECT id FROM hosts WHERE status = 'active'
),
host_counts AS (
    SELECT COUNT(*)::int AS total_hosts FROM active_hosts
),
hosts_needing_updates AS (
    SELECT COUNT(DISTINCT hp.host_id)::int AS cnt
    FROM host_packages hp
    JOIN active_hosts ah ON ah.id = hp.host_id
    WHERE hp.needs_update = true
),
hosts_with_security AS (
    SELECT COUNT(DISTINCT hp.host_id)::int AS cnt
    FROM host_packages hp
    JOIN active_hosts ah ON ah.id = hp.host_id
    WHERE hp.needs_update = true AND hp.is_security_update = true
),
package_counts AS (
    SELECT
        COUNT(DISTINCT package_id)::int AS total_outdated,
        COUNT(DISTINCT package_id) FILTER (WHERE is_security_update)::int AS security_updates
    FROM host_packages
    WHERE needs_update = true
)
SELECT
    hc.total_hosts,
    hnu.cnt AS hosts_needing_updates,
    pc.total_outdated AS total_outdated_packages,
    pc.security_updates AS security_updates,
    hws.cnt AS hosts_with_security_updates,
    (SELECT COUNT(*)::int FROM repositories WHERE is_active = true) AS total_repos,
    (SELECT COUNT(*)::int FROM update_history WHERE timestamp >= $1 AND status = 'success') AS recent_updates_24h
FROM host_counts hc
CROSS JOIN hosts_needing_updates hnu
CROSS JOIN hosts_with_security hws
CROSS JOIN package_counts pc
`

type GetHomepageStatsRow struct {
	TotalHosts               int32 `json:"total_hosts"`
	HostsNeedingUpdates      int32 `json:"hosts_needing_updates"`
	TotalOutdatedPackages    int32 `json:"total_outdated_packages"`
	SecurityUpdates          int32 `json:"security_updates"`
	HostsWithSecurityUpdates int32 `json:"hosts_with_security_updates"`
	TotalRepos               int32 `json:"total_repos"`
	RecentUpdates24h         int32 `json:"recent_updates_24h"`
}

func (q *Queries) GetHomepageStats(ctx context.Context, since pgtype.Timestamp) (GetHomepageStatsRow, error) {
	row := q.db.QueryRow(ctx, getHomepageStats, since)
	var i GetHomepageStatsRow
	err := row.Scan(
		&i.TotalHosts,
		&i.HostsNeedingUpdates,
		&i.TotalOutdatedPackages,
		&i.SecurityUpdates,
		&i.HostsWithSecurityUpdates,
		&i.TotalRepos,
		&i.RecentUpdates24h,
	)
	return i, err
}

const getHostPackageStats = `-- name: GetHostPackageStats :one
SELECT COUNT(*)::int, COUNT(*) FILTER (WHERE needs_update)::int, COUNT(*) FILTER (WHERE needs_update AND is_security_update)::int
FROM host_packages WHERE host_id = $1
`

type GetHostPackageStatsRow struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int32 `json:"column_3"`
}

func (q *Queries) GetHostPackageStats(ctx context.Context, hostID string) (GetHostPackageStatsRow, error) {
	row := q.db.QueryRow(ctx, getHostPackageStats, hostID)
	var i GetHostPackageStatsRow
	err := row.Scan(&i.Column1, &i.Column2, &i.Column3)
	return i, err
}

const getHostPackagesForScopedApi = `-- name: GetHostPackagesForScopedApi :many
SELECT hp.id, hp.host_id, hp.package_id, hp.current_version, hp.available_version,
    hp.needs_update, hp.is_security_update, hp.last_checked,
    p.name as pkg_name, p.description as pkg_description, p.category as pkg_category
FROM host_packages hp
JOIN packages p ON p.id = hp.package_id
WHERE hp.host_id = $1
ORDER BY hp.is_security_update DESC, hp.needs_update DESC
`

type GetHostPackagesForScopedApiRow struct {
	ID               string           `json:"id"`
	HostID           string           `json:"host_id"`
	PackageID        string           `json:"package_id"`
	CurrentVersion   string           `json:"current_version"`
	AvailableVersion *string          `json:"available_version"`
	NeedsUpdate      bool             `json:"needs_update"`
	IsSecurityUpdate bool             `json:"is_security_update"`
	LastChecked      pgtype.Timestamp `json:"last_checked"`
	PkgName          string           `json:"pkg_name"`
	PkgDescription   *string          `json:"pkg_description"`
	PkgCategory      *string          `json:"pkg_category"`
}

func (q *Queries) GetHostPackagesForScopedApi(ctx context.Context, hostID string) ([]GetHostPackagesForScopedApiRow, error) {
	rows, err := q.db.Query(ctx, getHostPackagesForScopedApi, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostPackagesForScopedApiRow
	for rows.Next() {
		var i GetHostPackagesForScopedApiRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackageID,
			&i.CurrentVersion,
			&i.AvailableVersion,
			&i.NeedsUpdate,
			&i.IsSecurityUpdate,
			&i.LastChecked,
			&i.PkgName,
			&i.PkgDescription,
			&i.PkgCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostPackagesWithPackages = `-- name: GetHostPackagesWithPackages :many
SELECT hp.id, hp.host_id, hp.package_id, hp.current_version, hp.available_version,
    hp.needs_update, hp.is_security_update, hp.last_checked,
    p.name as pkg_name
FROM host_packages hp
JOIN packages p ON p.id = hp.package_id
WHERE hp.host_id = $1
ORDER BY hp.needs_update DESC
`

type GetHostPackagesWithPackagesRow struct {
	ID               string           `json:"id"`
	HostID           string           `json:"host_id"`
	PackageID        string           `json:"package_id"`
	CurrentVersion   string           `json:"current_version"`
	AvailableVersion *string          `json:"available_version"`
	NeedsUpdate      bool             `json:"needs_update"`
	IsSecurityUpdate bool             `json:"is_security_update"`
	LastChecked      pgtype.Timestamp `json:"last_checked"`
	PkgName          string           `json:"pkg_name"`
}

func (q *Queries) GetHostPackagesWithPackages(ctx context.Context, hostID string) ([]GetHostPackagesWithPackagesRow, error) {
	rows, err := q.db.Query(ctx, getHostPackagesWithPackages, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostPackagesWithPackagesRow
	for rows.Next() {
		var i GetHostPackagesWithPackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackageID,
			&i.CurrentVersion,
			&i.AvailableVersion,
			&i.NeedsUpdate,
			&i.IsSecurityUpdate,
			&i.LastChecked,
			&i.PkgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostsForPackageTrends = `-- name: GetHostsForPackageTrends :many
SELECT id, friendly_name, hostname
FROM hosts
ORDER BY friendly_name ASC
`

type GetHostsForPackageTrendsRow struct {
	ID           string  `json:"id"`
	FriendlyName string  `json:"friendly_name"`
	Hostname     *string `json:"hostname"`
}

func (q *Queries) GetHostsForPackageTrends(ctx context.Context) ([]GetHostsForPackageTrendsRow, error) {
	rows, err := q.db.Query(ctx, getHostsForPackageTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostsForPackageTrendsRow
	for rows.Next() {
		var i GetHostsForPackageTrendsRow
		if err := rows.Scan(&i.ID, &i.FriendlyName, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostsWithCounts = `-- name: GetHostsWithCounts :many
SELECT h.id, h.machine_id, h.friendly_name, h.hostname, h.ip, h.os_type, h.os_version,
    h.status, h.agent_version, h.auto_update, h.notes, h.api_id,
    h.needs_reboot, h.reboot_reason, h.allow_reboot, h.system_uptime, h.docker_enabled, h.compliance_enabled, h.compliance_on_demand_only,
    h.last_update,
    h.compliance_scanner_status->'scanner_info'->>'ssg_version' as ssg_version,
    COALESCE(uc.cnt, 0)::int as updates_count,
    COALESCE(sc.cnt, 0)::int as security_updates_count,
    COALESCE(tc.cnt, 0)::int as total_packages_count
FROM hosts h
LEFT JOIN (SELECT host_id, COUNT(*) as cnt FROM host_packages WHERE needs_update = true GROUP BY host_id) uc ON uc.host_id = h.id
LEFT JOIN (SELECT host_id, COUNT(*) as cnt FROM host_packages WHERE needs_update = true AND is_security_update = true GROUP BY host_id) sc ON sc.host_id = h.id
LEFT JOIN (SELECT host_id, COUNT(*) as cnt FROM host_packages GROUP BY host_id) tc ON tc.host_id = h.id
WHERE ($1::text IS NULL OR h.friendly_name ILIKE '%' || $1 || '%' OR h.hostname ILIKE '%' || $1 || '%' OR h.ip ILIKE '%' || $1 || '%' OR h.os_type ILIKE '%' || $1 || '%' OR h.notes ILIKE '%' || $1 || '%')
AND (
    $2::text IS NULL
    OR ($2 = 'ungrouped' AND NOT EXISTS (SELECT 1 FROM host_group_memberships hgm WHERE hgm.host_id = h.id))
    OR ($2 != 'ungrouped' AND EXISTS (SELECT 1 FROM host_group_memberships hgm WHERE hgm.host_id = h.id AND hgm.host_group_id = $2))
)
AND ($3::text IS NULL OR h.status = $3)
AND ($4::text IS NULL OR h.os_type ILIKE $4)
AND ($5::text IS NULL OR h.os_version ILIKE $5)
ORDER BY h.last_update DESC NULLS LAST
`

type GetHostsWithCountsParams struct {
	Search    *string `json:"search"`
	Group     *string `json:"group"`
	Status    *string `json:"status"`
	Os        *string `json:"os"`
	OsVersion *string `json:"os_version"`
}

type GetHostsWithCountsRow struct {
	ID                     string           `json:"id"`
	MachineID              *string          `json:"machine_id"`
	FriendlyName           string           `json:"friendly_name"`
	Hostname               *string          `json:"hostname"`
	Ip                     *string          `json:"ip"`
	OsType                 string           `json:"os_type"`
	OsVersion              string           `json:"os_version"`
	Status                 string           `json:"status"`
	AgentVersion           *string          `json:"agent_version"`
	AutoUpdate             bool             `json:"auto_update"`
	Notes                  *string          `json:"notes"`
	ApiID                  string           `json:"api_id"`
	NeedsReboot            *bool            `json:"needs_reboot"`
	RebootReason           *string          `json:"reboot_reason"`
	AllowReboot            bool             `json:"allow_reboot"`
	SystemUptime           *string          `json:"system_uptime"`
	DockerEnabled          bool             `json:"docker_enabled"`
	ComplianceEnabled      bool             `json:"compliance_enabled"`
	ComplianceOnDemandOnly bool             `json:"compliance_on_demand_only"`
	LastUpdate             pgtype.Timestamp `json:"last_update"`
	SsgVersion             interface{}      `json:"ssg_version"`
	UpdatesCount           int32            `json:"updates_count"`
	SecurityUpdatesCount   int32            `json:"security_updates_count"`
	TotalPackagesCount     int32            `json:"total_packages_count"`
}

func (q *Queries) GetHostsWithCounts(ctx context.Context, arg GetHostsWithCountsParams) ([]GetHostsWithCountsRow, error) {
	rows, err := q.db.Query(ctx, getHostsWithCounts,
		arg.Search,
		arg.Group,
		arg.Status,
		arg.Os,
		arg.OsVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostsWithCountsRow
	for rows.Next() {
		var i GetHostsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.FriendlyName,
			&i.Hostname,
			&i.Ip,
			&i.OsType,
			&i.OsVersion,
			&i.Status,
			&i.AgentVersion,
			&i.AutoUpdate,
			&i.Notes,
			&i.ApiID,
			&i.NeedsReboot,
			&i.RebootReason,
			&i.AllowReboot,
			&i.SystemUptime,
			&i.DockerEnabled,
			&i.ComplianceEnabled,
			&i.ComplianceOnDemandOnly,
			&i.LastUpdate,
			&i.SsgVersion,
			&i.UpdatesCount,
			&i.SecurityUpdatesCount,
			&i.TotalPackagesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOSDistribution = `-- name: GetOSDistribution :many
SELECT os_type as name, COUNT(*)::int as count FROM hosts WHERE status = 'active' GROUP BY os_type
`

type GetOSDistributionRow struct {
	Name  string `json:"name"`
	Count int32  `json:"count"`
}

func (q *Queries) GetOSDistribution(ctx context.Context) ([]GetOSDistributionRow, error) {
	rows, err := q.db.Query(ctx, getOSDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOSDistributionRow
	for rows.Next() {
		var i GetOSDistributionRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOSDistributionByTypeAndVersion = `-- name: GetOSDistributionByTypeAndVersion :many
SELECT os_type, os_version,
    (os_type || ' ' || os_version)::text as name,
    COUNT(*)::int as count
FROM hosts
WHERE status = 'active'
GROUP BY os_type, os_version
ORDER BY count DESC, os_type, os_version
`

type GetOSDistributionByTypeAndVersionRow struct {
	OsType    string `json:"os_type"`
	OsVersion string `json:"os_version"`
	Name      string `json:"name"`
	Count     int32  `json:"count"`
}

func (q *Queries) GetOSDistributionByTypeAndVersion(ctx context.Context) ([]GetOSDistributionByTypeAndVersionRow, error) {
	rows, err := q.db.Query(ctx, getOSDistributionByTypeAndVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOSDistributionByTypeAndVersionRow
	for rows.Next() {
		var i GetOSDistributionByTypeAndVersionRow
		if err := rows.Scan(
			&i.OsType,
			&i.OsVersion,
			&i.Name,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentHosts = `-- name: GetRecentHosts :many
SELECT id, friendly_name, hostname, last_update, status
FROM hosts ORDER BY last_update DESC LIMIT $1
`

type GetRecentHostsRow struct {
	ID           string           `json:"id"`
	FriendlyName string           `json:"friendly_name"`
	Hostname     *string          `json:"hostname"`
	LastUpdate   pgtype.Timestamp `json:"last_update"`
	Status       string           `json:"status"`
}

func (q *Queries) GetRecentHosts(ctx context.Context, limit int32) ([]GetRecentHostsRow, error) {
	rows, err := q.db.Query(ctx, getRecentHosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentHostsRow
	for rows.Next() {
		var i GetRecentHostsRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendlyName,
			&i.Hostname,
			&i.LastUpdate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentUsers = `-- name: GetRecentUsers :many
SELECT id, username, email, first_name, last_name, role, last_login, created_at, avatar_url
FROM users WHERE last_login IS NOT NULL ORDER BY last_login DESC LIMIT $1
`

type GetRecentUsersRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	FirstName *string          `json:"first_name"`
	LastName  *string          `json:"last_name"`
	Role      string           `json:"role"`
	LastLogin pgtype.Timestamp `json:"last_login"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	AvatarUrl *string          `json:"avatar_url"`
}

func (q *Queries) GetRecentUsers(ctx context.Context, limit int32) ([]GetRecentUsersRow, error) {
	rows, err := q.db.Query(ctx, getRecentUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentUsersRow
	for rows.Next() {
		var i GetRecentUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.LastLogin,
			&i.CreatedAt,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateHistory = `-- name: GetUpdateHistory :many
SELECT id, host_id, packages_count, security_count, total_packages,
    payload_size_kb, execution_time, timestamp, status, error_message
FROM update_history
WHERE host_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type GetUpdateHistoryParams struct {
	HostID string `json:"host_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetUpdateHistory(ctx context.Context, arg GetUpdateHistoryParams) ([]UpdateHistory, error) {
	rows, err := q.db.Query(ctx, getUpdateHistory, arg.HostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpdateHistory
	for rows.Next() {
		var i UpdateHistory
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackagesCount,
			&i.SecurityCount,
			&i.TotalPackages,
			&i.PayloadSizeKb,
			&i.ExecutionTime,
			&i.Timestamp,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateHistoryDaily = `-- name: GetUpdateHistoryDaily :many
SELECT DATE(timestamp)::text as ts,
    MAX(packages_count)::int as packages_count,
    MAX(security_count)::int as security_count,
    MAX(COALESCE(total_packages, 0))::int as total_packages
FROM update_history
WHERE host_id = $1 AND timestamp >= $2 AND timestamp <= $3 AND status = 'success'
  AND COALESCE(total_packages, 0) >= 0
  AND packages_count >= 0
  AND security_count >= 0
  AND security_count <= packages_count
GROUP BY DATE(timestamp)
ORDER BY ts
`

type GetUpdateHistoryDailyParams struct {
	HostID      string           `json:"host_id"`
	Timestamp   pgtype.Timestamp `json:"timestamp"`
	Timestamp_2 pgtype.Timestamp `json:"timestamp_2"`
}

type GetUpdateHistoryDailyRow struct {
	Ts            string `json:"ts"`
	PackagesCount int32  `json:"packages_count"`
	SecurityCount int32  `json:"security_count"`
	TotalPackages int32  `json:"total_packages"`
}

func (q *Queries) GetUpdateHistoryDaily(ctx context.Context, arg GetUpdateHistoryDailyParams) ([]GetUpdateHistoryDailyRow, error) {
	rows, err := q.db.Query(ctx, getUpdateHistoryDaily, arg.HostID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdateHistoryDailyRow
	for rows.Next() {
		var i GetUpdateHistoryDailyRow
		if err := rows.Scan(
			&i.Ts,
			&i.PackagesCount,
			&i.SecurityCount,
			&i.TotalPackages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateTrends = `-- name: GetUpdateTrends :many
SELECT DATE(timestamp) as ts, COUNT(*)::int as cnt,
    COALESCE(SUM(packages_count), 0)::int as pkg_sum,
    COALESCE(SUM(security_count), 0)::int as sec_sum
FROM update_history
WHERE timestamp >= $1
GROUP BY DATE(timestamp)
ORDER BY ts
`

type GetUpdateTrendsRow struct {
	Ts     pgtype.Date `json:"ts"`
	Cnt    int32       `json:"cnt"`
	PkgSum int32       `json:"pkg_sum"`
	SecSum int32       `json:"sec_sum"`
}

func (q *Queries) GetUpdateTrends(ctx context.Context, timestamp pgtype.Timestamp) ([]GetUpdateTrendsRow, error) {
	rows, err := q.db.Query(ctx, getUpdateTrends, timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdateTrendsRow
	for rows.Next() {
		var i GetUpdateTrendsRow
		if err := rows.Scan(
			&i.Ts,
			&i.Cnt,
			&i.PkgSum,
			&i.SecSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdateHistoryByDateRange = `-- name: ListUpdateHistoryByDateRange :many
SELECT id, host_id, packages_count, security_count, total_packages,
    payload_size_kb, execution_time, timestamp, status, error_message
FROM update_history
WHERE host_id = $1 AND timestamp >= $2 AND timestamp <= $3 AND status = 'success'
ORDER BY timestamp ASC
`

type ListUpdateHistoryByDateRangeParams struct {
	HostID      string           `json:"host_id"`
	Timestamp   pgtype.Timestamp `json:"timestamp"`
	Timestamp_2 pgtype.Timestamp `json:"timestamp_2"`
}

func (q *Queries) ListUpdateHistoryByDateRange(ctx context.Context, arg ListUpdateHistoryByDateRangeParams) ([]UpdateHistory, error) {
	rows, err := q.db.Query(ctx, listUpdateHistoryByDateRange, arg.HostID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpdateHistory
	for rows.Next() {
		var i UpdateHistory
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackagesCount,
			&i.SecurityCount,
			&i.TotalPackages,
			&i.PayloadSizeKb,
			&i.ExecutionTime,
			&i.Timestamp,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
