// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fork_report_archive.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const forkAbandonStaleReportArchive = `-- name: ForkAbandonStaleReportArchive :execrows
UPDATE fork_report_archive
SET status = 'failed', error_code = 'abandoned', error_message = 'run did not finish within 24 hours', finished_at = NOW()
WHERE scheduled_report_id = $1 AND status = 'pending' AND created_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) ForkAbandonStaleReportArchive(ctx context.Context, scheduledReportID string) (int64, error) {
	result, err := q.db.Exec(ctx, forkAbandonStaleReportArchive, scheduledReportID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forkClaimScheduledReportSlot = `-- name: ForkClaimScheduledReportSlot :execrows

UPDATE scheduled_reports
SET last_run_at = $1, next_run_at = $2, updated_at = NOW()
WHERE id = $3 AND enabled = true
  AND date_trunc('second', next_run_at) = date_trunc('second', $4::timestamp)
`

type ForkClaimScheduledReportSlotParams struct {
	Now  pgtype.Timestamp `json:"now"`
	Next pgtype.Timestamp `json:"next"`
	ID   string           `json:"id"`
	Slot pgtype.Timestamp `json:"slot"`
}

// Fork: customer reports (increment D). Slot claim on scheduled_reports,
// recipients, run archive and per-delivery status. List queries never read
// pdf/html/csv. All timestamps on the fork tables are TIMESTAMPTZ (Go
// time.Time / *time.Time via the sqlc override); scheduled_reports keeps the
// upstream TIMESTAMP(3) columns (pgtype.Timestamp via pgtime.From).
// Atomic slot claim: succeeds only while next_run_at still points at the slot
// the task was enqueued for. Compared at second precision because
// notifications.NextCronRun yields whole seconds and legacy rows may carry ms.
func (q *Queries) ForkClaimScheduledReportSlot(ctx context.Context, arg ForkClaimScheduledReportSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, forkClaimScheduledReportSlot,
		arg.Now,
		arg.Next,
		arg.ID,
		arg.Slot,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forkFinishReportArchive = `-- name: ForkFinishReportArchive :execrows
UPDATE fork_report_archive
SET status = $1, error_code = $2, error_message = $3, finished_at = NOW()
WHERE id = $4 AND status = 'pending'
`

type ForkFinishReportArchiveParams struct {
	Status       string  `json:"status"`
	ErrorCode    *string `json:"error_code"`
	ErrorMessage *string `json:"error_message"`
	ID           string  `json:"id"`
}

// Only a pending row transitions; a second finalize of the same run is a no-op.
func (q *Queries) ForkFinishReportArchive(ctx context.Context, arg ForkFinishReportArchiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, forkFinishReportArchive,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forkGetReportArchiveByRunKey = `-- name: ForkGetReportArchiveByRunKey :one
SELECT id, scheduled_report_id, run_key, trigger_kind, slot_at, created_at, finished_at, status, error_code, error_message,
       report_name, language, period_from, period_to, group_ids, group_names, host_count, customer_mode,
       smtp_destination_id, mail_from, recipients, pdf_size, pdf_sha256, (pdf IS NOT NULL)::boolean AS has_pdf
FROM fork_report_archive WHERE run_key = $1
`

type ForkGetReportArchiveByRunKeyRow struct {
	ID                string     `json:"id"`
	ScheduledReportID string     `json:"scheduled_report_id"`
	RunKey            string     `json:"run_key"`
	TriggerKind       string     `json:"trigger_kind"`
	SlotAt            *time.Time `json:"slot_at"`
	CreatedAt         time.Time  `json:"created_at"`
	FinishedAt        *time.Time `json:"finished_at"`
	Status            string     `json:"status"`
	ErrorCode         *string    `json:"error_code"`
	ErrorMessage      *string    `json:"error_message"`
	ReportName        string     `json:"report_name"`
	Language          string     `json:"language"`
	PeriodFrom        *time.Time `json:"period_from"`
	PeriodTo          *time.Time `json:"period_to"`
	GroupIds          []string   `json:"group_ids"`
	GroupNames        []string   `json:"group_names"`
	HostCount         int32      `json:"host_count"`
	CustomerMode      bool       `json:"customer_mode"`
	SmtpDestinationID *string    `json:"smtp_destination_id"`
	MailFrom          *string    `json:"mail_from"`
	Recipients        []string   `json:"recipients"`
	PdfSize           int32      `json:"pdf_size"`
	PdfSha256         *string    `json:"pdf_sha256"`
	HasPdf            bool       `json:"has_pdf"`
}

func (q *Queries) ForkGetReportArchiveByRunKey(ctx context.Context, runKey string) (ForkGetReportArchiveByRunKeyRow, error) {
	row := q.db.QueryRow(ctx, forkGetReportArchiveByRunKey, runKey)
	var i ForkGetReportArchiveByRunKeyRow
	err := row.Scan(
		&i.ID,
		&i.ScheduledReportID,
		&i.RunKey,
		&i.TriggerKind,
		&i.SlotAt,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ReportName,
		&i.Language,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.GroupIds,
		&i.GroupNames,
		&i.HostCount,
		&i.CustomerMode,
		&i.SmtpDestinationID,
		&i.MailFrom,
		&i.Recipients,
		&i.PdfSize,
		&i.PdfSha256,
		&i.HasPdf,
	)
	return i, err
}

const forkGetReportArchiveContent = `-- name: ForkGetReportArchiveContent :one
SELECT id, scheduled_report_id, status, report_name, language, customer_mode, smtp_destination_id, mail_from, recipients,
       subject, COALESCE(html, '')::text AS html, COALESCE(csv, '')::text AS csv, pdf, pdf_sha256, created_at
FROM fork_report_archive WHERE id = $1
`

type ForkGetReportArchiveContentRow struct {
	ID                string    `json:"id"`
	ScheduledReportID string    `json:"scheduled_report_id"`
	Status            string    `json:"status"`
	ReportName        string    `json:"report_name"`
	Language          string    `json:"language"`
	CustomerMode      bool      `json:"customer_mode"`
	SmtpDestinationID *string   `json:"smtp_destination_id"`
	MailFrom          *string   `json:"mail_from"`
	Recipients        []string  `json:"recipients"`
	Subject           string    `json:"subject"`
	Html              string    `json:"html"`
	Csv               string    `json:"csv"`
	Pdf               []byte    `json:"pdf"`
	PdfSha256         *string   `json:"pdf_sha256"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) ForkGetReportArchiveContent(ctx context.Context, id string) (ForkGetReportArchiveContentRow, error) {
	row := q.db.QueryRow(ctx, forkGetReportArchiveContent, id)
	var i ForkGetReportArchiveContentRow
	err := row.Scan(
		&i.ID,
		&i.ScheduledReportID,
		&i.Status,
		&i.ReportName,
		&i.Language,
		&i.CustomerMode,
		&i.SmtpDestinationID,
		&i.MailFrom,
		&i.Recipients,
		&i.Subject,
		&i.Html,
		&i.Csv,
		&i.Pdf,
		&i.PdfSha256,
		&i.CreatedAt,
	)
	return i, err
}

const forkGetReportArchivePDF = `-- name: ForkGetReportArchivePDF :one
SELECT a.id, a.scheduled_report_id, a.report_name, a.created_at, a.status, a.pdf, s.timezone
FROM fork_report_archive a JOIN scheduled_reports s ON s.id = a.scheduled_report_id
WHERE a.id = $1 AND a.pdf IS NOT NULL
`

type ForkGetReportArchivePDFRow struct {
	ID                string    `json:"id"`
	ScheduledReportID string    `json:"scheduled_report_id"`
	ReportName        string    `json:"report_name"`
	CreatedAt         time.Time `json:"created_at"`
	Status            string    `json:"status"`
	Pdf               []byte    `json:"pdf"`
	Timezone          string    `json:"timezone"`
}

func (q *Queries) ForkGetReportArchivePDF(ctx context.Context, id string) (ForkGetReportArchivePDFRow, error) {
	row := q.db.QueryRow(ctx, forkGetReportArchivePDF, id)
	var i ForkGetReportArchivePDFRow
	err := row.Scan(
		&i.ID,
		&i.ScheduledReportID,
		&i.ReportName,
		&i.CreatedAt,
		&i.Status,
		&i.Pdf,
		&i.Timezone,
	)
	return i, err
}

const forkGetScheduledReportForUpdate = `-- name: ForkGetScheduledReportForUpdate :one
SELECT id, name, cron_expr, enabled, definition, destination_ids, timezone, next_run_at, last_run_at, created_at, updated_at, fork_email_recipients FROM scheduled_reports WHERE id = $1 FOR UPDATE
`

// Row lock for the update handler, so a concurrent slot claim is never
// overwritten with stale next_run_at/last_run_at values.
func (q *Queries) ForkGetScheduledReportForUpdate(ctx context.Context, id string) (ScheduledReport, error) {
	row := q.db.QueryRow(ctx, forkGetScheduledReportForUpdate, id)
	var i ScheduledReport
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpr,
		&i.Enabled,
		&i.Definition,
		&i.DestinationIds,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForkEmailRecipients,
	)
	return i, err
}

const forkInsertReportArchive = `-- name: ForkInsertReportArchive :exec
INSERT INTO fork_report_archive (id, scheduled_report_id, run_key, trigger_kind, slot_at, report_name, language, customer_mode, group_ids, recipients)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8,
        COALESCE($9::text[], '{}'::text[]), COALESCE($10::text[], '{}'::text[]))
`

type ForkInsertReportArchiveParams struct {
	ID                string     `json:"id"`
	ScheduledReportID string     `json:"scheduled_report_id"`
	RunKey            string     `json:"run_key"`
	TriggerKind       string     `json:"trigger_kind"`
	SlotAt            *time.Time `json:"slot_at"`
	ReportName        string     `json:"report_name"`
	Language          string     `json:"language"`
	CustomerMode      bool       `json:"customer_mode"`
	GroupIds          []string   `json:"group_ids"`
	Recipients        []string   `json:"recipients"`
}

func (q *Queries) ForkInsertReportArchive(ctx context.Context, arg ForkInsertReportArchiveParams) error {
	_, err := q.db.Exec(ctx, forkInsertReportArchive,
		arg.ID,
		arg.ScheduledReportID,
		arg.RunKey,
		arg.TriggerKind,
		arg.SlotAt,
		arg.ReportName,
		arg.Language,
		arg.CustomerMode,
		arg.GroupIds,
		arg.Recipients,
	)
	return err
}

const forkInsertReportDelivery = `-- name: ForkInsertReportDelivery :exec
INSERT INTO fork_report_deliveries (id, archive_id, destination_id, destination_name, channel, recipient)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (archive_id, destination_id, recipient) DO NOTHING
`

type ForkInsertReportDeliveryParams struct {
	ID              string `json:"id"`
	ArchiveID       string `json:"archive_id"`
	DestinationID   string `json:"destination_id"`
	DestinationName string `json:"destination_name"`
	Channel         string `json:"channel"`
	Recipient       string `json:"recipient"`
}

func (q *Queries) ForkInsertReportDelivery(ctx context.Context, arg ForkInsertReportDeliveryParams) error {
	_, err := q.db.Exec(ctx, forkInsertReportDelivery,
		arg.ID,
		arg.ArchiveID,
		arg.DestinationID,
		arg.DestinationName,
		arg.Channel,
		arg.Recipient,
	)
	return err
}

const forkListReportArchive = `-- name: ForkListReportArchive :many
SELECT id, scheduled_report_id, run_key, trigger_kind, slot_at, created_at, finished_at, status, error_code, error_message,
       report_name, language, period_from, period_to, group_ids, group_names, host_count, customer_mode,
       smtp_destination_id, mail_from, recipients, pdf_size, pdf_sha256, (pdf IS NOT NULL)::boolean AS has_pdf
FROM fork_report_archive
WHERE scheduled_report_id = $1
ORDER BY created_at DESC, id
LIMIT $2
`

type ForkListReportArchiveParams struct {
	ScheduledReportID string `json:"scheduled_report_id"`
	Limit             int32  `json:"limit"`
}

type ForkListReportArchiveRow struct {
	ID                string     `json:"id"`
	ScheduledReportID string     `json:"scheduled_report_id"`
	RunKey            string     `json:"run_key"`
	TriggerKind       string     `json:"trigger_kind"`
	SlotAt            *time.Time `json:"slot_at"`
	CreatedAt         time.Time  `json:"created_at"`
	FinishedAt        *time.Time `json:"finished_at"`
	Status            string     `json:"status"`
	ErrorCode         *string    `json:"error_code"`
	ErrorMessage      *string    `json:"error_message"`
	ReportName        string     `json:"report_name"`
	Language          string     `json:"language"`
	PeriodFrom        *time.Time `json:"period_from"`
	PeriodTo          *time.Time `json:"period_to"`
	GroupIds          []string   `json:"group_ids"`
	GroupNames        []string   `json:"group_names"`
	HostCount         int32      `json:"host_count"`
	CustomerMode      bool       `json:"customer_mode"`
	SmtpDestinationID *string    `json:"smtp_destination_id"`
	MailFrom          *string    `json:"mail_from"`
	Recipients        []string   `json:"recipients"`
	PdfSize           int32      `json:"pdf_size"`
	PdfSha256         *string    `json:"pdf_sha256"`
	HasPdf            bool       `json:"has_pdf"`
}

func (q *Queries) ForkListReportArchive(ctx context.Context, arg ForkListReportArchiveParams) ([]ForkListReportArchiveRow, error) {
	rows, err := q.db.Query(ctx, forkListReportArchive, arg.ScheduledReportID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkListReportArchiveRow
	for rows.Next() {
		var i ForkListReportArchiveRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledReportID,
			&i.RunKey,
			&i.TriggerKind,
			&i.SlotAt,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ReportName,
			&i.Language,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.GroupIds,
			&i.GroupNames,
			&i.HostCount,
			&i.CustomerMode,
			&i.SmtpDestinationID,
			&i.MailFrom,
			&i.Recipients,
			&i.PdfSize,
			&i.PdfSha256,
			&i.HasPdf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkListReportDeliveries = `-- name: ForkListReportDeliveries :many
SELECT id, archive_id, destination_id, destination_name, channel, recipient, status, error_code, error_message, attempts, sent_at FROM fork_report_deliveries WHERE archive_id = $1 ORDER BY channel, destination_id, recipient, id
`

func (q *Queries) ForkListReportDeliveries(ctx context.Context, archiveID string) ([]ForkReportDelivery, error) {
	rows, err := q.db.Query(ctx, forkListReportDeliveries, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportDelivery
	for rows.Next() {
		var i ForkReportDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.DestinationID,
			&i.DestinationName,
			&i.Channel,
			&i.Recipient,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Attempts,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkListReportDeliveriesForReport = `-- name: ForkListReportDeliveriesForReport :many
SELECT d.id, d.archive_id, d.destination_id, d.destination_name, d.channel, d.recipient, d.status, d.error_code, d.error_message, d.attempts, d.sent_at FROM fork_report_deliveries d
JOIN fork_report_archive a ON a.id = d.archive_id
WHERE a.scheduled_report_id = $1
ORDER BY a.created_at DESC, d.channel, d.destination_id, d.recipient, d.id
`

func (q *Queries) ForkListReportDeliveriesForReport(ctx context.Context, scheduledReportID string) ([]ForkReportDelivery, error) {
	rows, err := q.db.Query(ctx, forkListReportDeliveriesForReport, scheduledReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportDelivery
	for rows.Next() {
		var i ForkReportDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.DestinationID,
			&i.DestinationName,
			&i.Channel,
			&i.Recipient,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Attempts,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkMarkReportDelivery = `-- name: ForkMarkReportDelivery :exec
UPDATE fork_report_deliveries
SET status = $1, error_code = $2, error_message = $3,
    attempts = attempts + 1,
    sent_at = CASE WHEN $1::text = 'sent' THEN NOW() ELSE sent_at END
WHERE id = $4 AND status <> 'sent'
`

type ForkMarkReportDeliveryParams struct {
	Status       string  `json:"status"`
	ErrorCode    *string `json:"error_code"`
	ErrorMessage *string `json:"error_message"`
	ID           string  `json:"id"`
}

func (q *Queries) ForkMarkReportDelivery(ctx context.Context, arg ForkMarkReportDeliveryParams) error {
	_, err := q.db.Exec(ctx, forkMarkReportDelivery,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const forkPruneReportArchive = `-- name: ForkPruneReportArchive :execrows
DELETE FROM fork_report_archive AS fra
WHERE fra.scheduled_report_id = $1
  AND fra.id NOT IN (
      SELECT id FROM fork_report_archive
      WHERE scheduled_report_id = $1
      ORDER BY created_at DESC, id
      LIMIT $2
  )
  AND NOT (fra.status = 'pending' AND fra.created_at > NOW() - INTERVAL '24 hours')
`

type ForkPruneReportArchiveParams struct {
	ID   string `json:"id"`
	Keep int32  `json:"keep"`
}

func (q *Queries) ForkPruneReportArchive(ctx context.Context, arg ForkPruneReportArchiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, forkPruneReportArchive, arg.ID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forkSetScheduledReportNextRunIfNull = `-- name: ForkSetScheduledReportNextRunIfNull :execrows
UPDATE scheduled_reports SET next_run_at = $1, updated_at = NOW()
WHERE id = $2 AND next_run_at IS NULL
`

type ForkSetScheduledReportNextRunIfNullParams struct {
	Next pgtype.Timestamp `json:"next"`
	ID   string           `json:"id"`
}

func (q *Queries) ForkSetScheduledReportNextRunIfNull(ctx context.Context, arg ForkSetScheduledReportNextRunIfNullParams) (int64, error) {
	result, err := q.db.Exec(ctx, forkSetScheduledReportNextRunIfNull, arg.Next, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forkSetScheduledReportRecipients = `-- name: ForkSetScheduledReportRecipients :exec
UPDATE scheduled_reports SET fork_email_recipients = $1::text[], updated_at = NOW()
WHERE id = $2
`

type ForkSetScheduledReportRecipientsParams struct {
	Recipients []string `json:"recipients"`
	ID         string   `json:"id"`
}

func (q *Queries) ForkSetScheduledReportRecipients(ctx context.Context, arg ForkSetScheduledReportRecipientsParams) error {
	_, err := q.db.Exec(ctx, forkSetScheduledReportRecipients, arg.Recipients, arg.ID)
	return err
}

const forkSnapshotReportArchive = `-- name: ForkSnapshotReportArchive :exec
UPDATE fork_report_archive
SET period_from = $1, period_to = $2,
    group_ids = COALESCE($3::text[], '{}'::text[]),
    group_names = COALESCE($4::text[], '{}'::text[]), host_count = $5,
    smtp_destination_id = $6, mail_from = $7,
    report_name = $8, language = $9, customer_mode = $10,
    recipients = COALESCE($11::text[], '{}'::text[]),
    subject = $12, html = $13, csv = $14,
    pdf = $15, pdf_size = $16, pdf_sha256 = $17
WHERE id = $18
`

type ForkSnapshotReportArchiveParams struct {
	PeriodFrom        *time.Time `json:"period_from"`
	PeriodTo          *time.Time `json:"period_to"`
	GroupIds          []string   `json:"group_ids"`
	GroupNames        []string   `json:"group_names"`
	HostCount         int32      `json:"host_count"`
	SmtpDestinationID *string    `json:"smtp_destination_id"`
	MailFrom          *string    `json:"mail_from"`
	ReportName        string     `json:"report_name"`
	Language          string     `json:"language"`
	CustomerMode      bool       `json:"customer_mode"`
	Recipients        []string   `json:"recipients"`
	Subject           string     `json:"subject"`
	Html              *string    `json:"html"`
	Csv               *string    `json:"csv"`
	Pdf               []byte     `json:"pdf"`
	PdfSize           int32      `json:"pdf_size"`
	PdfSha256         *string    `json:"pdf_sha256"`
	ID                string     `json:"id"`
}

func (q *Queries) ForkSnapshotReportArchive(ctx context.Context, arg ForkSnapshotReportArchiveParams) error {
	_, err := q.db.Exec(ctx, forkSnapshotReportArchive,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.GroupIds,
		arg.GroupNames,
		arg.HostCount,
		arg.SmtpDestinationID,
		arg.MailFrom,
		arg.ReportName,
		arg.Language,
		arg.CustomerMode,
		arg.Recipients,
		arg.Subject,
		arg.Html,
		arg.Csv,
		arg.Pdf,
		arg.PdfSize,
		arg.PdfSha256,
		arg.ID,
	)
	return err
}
