// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fork_reports.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const forkReportAllHostIDs = `-- name: ForkReportAllHostIDs :many

SELECT id FROM hosts ORDER BY friendly_name, id
`

// Fork: queries for host-group-scoped scheduled reports (internal/reports).
// Every query filters by host_ids FIRST and only then aggregates, sorts or
// limits, so a report for one group can never see another group's data.
// Security/update counts use the same definition-update exclusion as the
// dashboard (fork_is_definition_update + PM_IGNORE_DEFINITION_UPDATES).
func (q *Queries) ForkReportAllHostIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, forkReportAllHostIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkReportComplianceLatest = `-- name: ForkReportComplianceLatest :many
SELECT cs.host_id, h.friendly_name, cs.profile_id, cp.name AS profile_name, cs.score, cs.passed, cs.failed, cs.completed_at
FROM (
    SELECT DISTINCT ON (host_id, profile_id) id, host_id, profile_id, score, passed, failed, completed_at
    FROM compliance_scans
    WHERE status = 'completed' AND host_id = ANY($1::text[])
    ORDER BY host_id, profile_id, completed_at DESC NULLS LAST
) cs
JOIN hosts h ON h.id = cs.host_id
JOIN compliance_profiles cp ON cp.id = cs.profile_id
ORDER BY cs.score ASC NULLS FIRST, h.friendly_name, cp.name
`

type ForkReportComplianceLatestRow struct {
	HostID       string           `json:"host_id"`
	FriendlyName string           `json:"friendly_name"`
	ProfileID    string           `json:"profile_id"`
	ProfileName  string           `json:"profile_name"`
	Score        *float64         `json:"score"`
	Passed       int32            `json:"passed"`
	Failed       int32            `json:"failed"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}

// Latest completed scan per host AND profile inside the scope.
func (q *Queries) ForkReportComplianceLatest(ctx context.Context, hostIds []string) ([]ForkReportComplianceLatestRow, error) {
	rows, err := q.db.Query(ctx, forkReportComplianceLatest, hostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportComplianceLatestRow
	for rows.Next() {
		var i ForkReportComplianceLatestRow
		if err := rows.Scan(
			&i.HostID,
			&i.FriendlyName,
			&i.ProfileID,
			&i.ProfileName,
			&i.Score,
			&i.Passed,
			&i.Failed,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkReportGroupsByIDs = `-- name: ForkReportGroupsByIDs :many
SELECT id, name FROM host_groups WHERE id = ANY($1::text[]) ORDER BY name, id
`

type ForkReportGroupsByIDsRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ForkReportGroupsByIDs(ctx context.Context, groupIds []string) ([]ForkReportGroupsByIDsRow, error) {
	rows, err := q.db.Query(ctx, forkReportGroupsByIDs, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportGroupsByIDsRow
	for rows.Next() {
		var i ForkReportGroupsByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkReportHosts = `-- name: ForkReportHosts :many
SELECT h.id, h.friendly_name, h.hostname, h.api_id, h.os_type, h.os_version, h.status,
       h.last_update, h.agent_version, h.needs_reboot, h.fork_boot_time, h.system_uptime,
       h.disk_details, h.fork_pkg_broken,
       COALESCE(uc.cnt, 0)::int AS updates_count,
       COALESCE(sc.cnt, 0)::int AS security_updates_count,
       COALESCE(lp.id, '')::text AS last_run_id, COALESCE(lp.status, '')::text AS last_run_status,
       lp.created_at AS last_run_created_at, lp.completed_at AS last_run_completed_at
FROM hosts h
LEFT JOIN (
    SELECT host_id, COUNT(*) AS cnt FROM host_packages
    WHERE host_id = ANY($1::text[]) AND needs_update = true
      AND NOT ($2::boolean AND fork_is_definition_update(wua_categories, wua_kb))
    GROUP BY host_id
) uc ON uc.host_id = h.id
LEFT JOIN (
    SELECT host_id, COUNT(*) AS cnt FROM host_packages
    WHERE host_id = ANY($1::text[]) AND needs_update = true AND is_security_update = true
      AND NOT ($2::boolean AND fork_is_definition_update(wua_categories, wua_kb))
    GROUP BY host_id
) sc ON sc.host_id = h.id
LEFT JOIN LATERAL (
    SELECT pr.id, pr.status, pr.created_at, pr.completed_at FROM patch_runs pr
    WHERE pr.host_id = h.id AND pr.dry_run = false ORDER BY pr.created_at DESC, pr.id LIMIT 1
) lp ON true
WHERE h.id = ANY($1::text[])
ORDER BY h.friendly_name, h.id
`

type ForkReportHostsParams struct {
	HostIds                 []string `json:"host_ids"`
	IgnoreDefinitionUpdates bool     `json:"ignore_definition_updates"`
}

type ForkReportHostsRow struct {
	ID                   string           `json:"id"`
	FriendlyName         string           `json:"friendly_name"`
	Hostname             *string          `json:"hostname"`
	ApiID                string           `json:"api_id"`
	OsType               string           `json:"os_type"`
	OsVersion            string           `json:"os_version"`
	Status               string           `json:"status"`
	LastUpdate           pgtype.Timestamp `json:"last_update"`
	AgentVersion         *string          `json:"agent_version"`
	NeedsReboot          *bool            `json:"needs_reboot"`
	ForkBootTime         *time.Time       `json:"fork_boot_time"`
	SystemUptime         *string          `json:"system_uptime"`
	DiskDetails          []byte           `json:"disk_details"`
	ForkPkgBroken        bool             `json:"fork_pkg_broken"`
	UpdatesCount         int32            `json:"updates_count"`
	SecurityUpdatesCount int32            `json:"security_updates_count"`
	LastRunID            string           `json:"last_run_id"`
	LastRunStatus        string           `json:"last_run_status"`
	LastRunCreatedAt     pgtype.Timestamp `json:"last_run_created_at"`
	LastRunCompletedAt   pgtype.Timestamp `json:"last_run_completed_at"`
}

// One row per scope host with update counters and the latest real patch run.
func (q *Queries) ForkReportHosts(ctx context.Context, arg ForkReportHostsParams) ([]ForkReportHostsRow, error) {
	rows, err := q.db.Query(ctx, forkReportHosts, arg.HostIds, arg.IgnoreDefinitionUpdates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportHostsRow
	for rows.Next() {
		var i ForkReportHostsRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendlyName,
			&i.Hostname,
			&i.ApiID,
			&i.OsType,
			&i.OsVersion,
			&i.Status,
			&i.LastUpdate,
			&i.AgentVersion,
			&i.NeedsReboot,
			&i.ForkBootTime,
			&i.SystemUptime,
			&i.DiskDetails,
			&i.ForkPkgBroken,
			&i.UpdatesCount,
			&i.SecurityUpdatesCount,
			&i.LastRunID,
			&i.LastRunStatus,
			&i.LastRunCreatedAt,
			&i.LastRunCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkReportOpenAlerts = `-- name: ForkReportOpenAlerts :many
SELECT a.id, a.type, a.severity, a.title, a.created_at,
       COALESCE(a.metadata->>'host_id', '')::text AS host_id,
       h.friendly_name AS host_name
FROM alerts a LEFT JOIN hosts h ON h.id = a.metadata->>'host_id'
WHERE a.is_active = true AND a.resolved_at IS NULL
  AND ((a.metadata->>'host_id') = ANY($1::text[])
       OR ($2::boolean AND (a.metadata->>'host_id') IS NULL))
ORDER BY a.created_at DESC, a.id
`

type ForkReportOpenAlertsParams struct {
	HostIds       []string `json:"host_ids"`
	IncludeGlobal bool     `json:"include_global"`
}

type ForkReportOpenAlertsRow struct {
	ID        string           `json:"id"`
	Type      string           `json:"type"`
	Severity  string           `json:"severity"`
	Title     string           `json:"title"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	HostID    string           `json:"host_id"`
	HostName  *string          `json:"host_name"`
}

// Host alerts carry the host only in metadata.host_id; global alerts have none.
func (q *Queries) ForkReportOpenAlerts(ctx context.Context, arg ForkReportOpenAlertsParams) ([]ForkReportOpenAlertsRow, error) {
	rows, err := q.db.Query(ctx, forkReportOpenAlerts, arg.HostIds, arg.IncludeGlobal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportOpenAlertsRow
	for rows.Next() {
		var i ForkReportOpenAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.Title,
			&i.CreatedAt,
			&i.HostID,
			&i.HostName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkReportPatchActivity = `-- name: ForkReportPatchActivity :many
SELECT pr.id, pr.host_id, h.friendly_name, pr.status, pr.patch_type, pr.dry_run, pr.packages_affected,
       pr.created_at, pr.completed_at
FROM patch_runs pr JOIN hosts h ON h.id = pr.host_id
WHERE pr.host_id = ANY($1::text[])
  AND pr.created_at >= $2::timestamp AND pr.created_at < $3::timestamp
ORDER BY pr.created_at DESC, pr.id LIMIT $4::int
`

type ForkReportPatchActivityParams struct {
	HostIds    []string         `json:"host_ids"`
	PeriodFrom pgtype.Timestamp `json:"period_from"`
	PeriodTo   pgtype.Timestamp `json:"period_to"`
	MaxRows    int32            `json:"max_rows"`
}

type ForkReportPatchActivityRow struct {
	ID               string           `json:"id"`
	HostID           string           `json:"host_id"`
	FriendlyName     string           `json:"friendly_name"`
	Status           string           `json:"status"`
	PatchType        string           `json:"patch_type"`
	DryRun           bool             `json:"dry_run"`
	PackagesAffected []byte           `json:"packages_affected"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	CompletedAt      pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) ForkReportPatchActivity(ctx context.Context, arg ForkReportPatchActivityParams) ([]ForkReportPatchActivityRow, error) {
	rows, err := q.db.Query(ctx, forkReportPatchActivity,
		arg.HostIds,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportPatchActivityRow
	for rows.Next() {
		var i ForkReportPatchActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.FriendlyName,
			&i.Status,
			&i.PatchType,
			&i.DryRun,
			&i.PackagesAffected,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkReportPatchRunStats = `-- name: ForkReportPatchRunStats :many
SELECT status, COUNT(*)::int AS cnt FROM patch_runs
WHERE host_id = ANY($1::text[]) AND dry_run = false
  AND created_at >= $2::timestamp AND created_at < $3::timestamp
GROUP BY status ORDER BY status
`

type ForkReportPatchRunStatsParams struct {
	HostIds    []string         `json:"host_ids"`
	PeriodFrom pgtype.Timestamp `json:"period_from"`
	PeriodTo   pgtype.Timestamp `json:"period_to"`
}

type ForkReportPatchRunStatsRow struct {
	Status string `json:"status"`
	Cnt    int32  `json:"cnt"`
}

func (q *Queries) ForkReportPatchRunStats(ctx context.Context, arg ForkReportPatchRunStatsParams) ([]ForkReportPatchRunStatsRow, error) {
	rows, err := q.db.Query(ctx, forkReportPatchRunStats, arg.HostIds, arg.PeriodFrom, arg.PeriodTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportPatchRunStatsRow
	for rows.Next() {
		var i ForkReportPatchRunStatsRow
		if err := rows.Scan(&i.Status, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkReportReboots = `-- name: ForkReportReboots :many
SELECT jh.id, jh.host_id, h.friendly_name, jh.status, jh.error_message, jh.created_at, jh.completed_at
FROM job_history jh LEFT JOIN hosts h ON h.id = jh.host_id
WHERE jh.job_name = 'reboot' AND jh.host_id = ANY($1::text[])
  AND jh.created_at >= $2::timestamp AND jh.created_at < $3::timestamp
ORDER BY jh.created_at DESC, jh.id LIMIT $4::int
`

type ForkReportRebootsParams struct {
	HostIds    []string         `json:"host_ids"`
	PeriodFrom pgtype.Timestamp `json:"period_from"`
	PeriodTo   pgtype.Timestamp `json:"period_to"`
	MaxRows    int32            `json:"max_rows"`
}

type ForkReportRebootsRow struct {
	ID           string           `json:"id"`
	HostID       *string          `json:"host_id"`
	FriendlyName *string          `json:"friendly_name"`
	Status       string           `json:"status"`
	ErrorMessage *string          `json:"error_message"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) ForkReportReboots(ctx context.Context, arg ForkReportRebootsParams) ([]ForkReportRebootsRow, error) {
	rows, err := q.db.Query(ctx, forkReportReboots,
		arg.HostIds,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportRebootsRow
	for rows.Next() {
		var i ForkReportRebootsRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.FriendlyName,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkReportRecentPatchRuns = `-- name: ForkReportRecentPatchRuns :many
SELECT pr.id, pr.host_id, h.friendly_name, h.hostname, pr.status, pr.patch_type, pr.package_name, pr.package_names,
       pr.created_at, pr.started_at, pr.completed_at
FROM patch_runs pr JOIN hosts h ON h.id = pr.host_id
WHERE pr.host_id = ANY($1::text[]) AND pr.dry_run = false
ORDER BY pr.created_at DESC, pr.id LIMIT $2::int
`

type ForkReportRecentPatchRunsParams struct {
	HostIds []string `json:"host_ids"`
	MaxRows int32    `json:"max_rows"`
}

type ForkReportRecentPatchRunsRow struct {
	ID           string           `json:"id"`
	HostID       string           `json:"host_id"`
	FriendlyName string           `json:"friendly_name"`
	Hostname     *string          `json:"hostname"`
	Status       string           `json:"status"`
	PatchType    string           `json:"patch_type"`
	PackageName  *string          `json:"package_name"`
	PackageNames []byte           `json:"package_names"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) ForkReportRecentPatchRuns(ctx context.Context, arg ForkReportRecentPatchRunsParams) ([]ForkReportRecentPatchRunsRow, error) {
	rows, err := q.db.Query(ctx, forkReportRecentPatchRuns, arg.HostIds, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportRecentPatchRunsRow
	for rows.Next() {
		var i ForkReportRecentPatchRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.FriendlyName,
			&i.Hostname,
			&i.Status,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forkReportSecurityUpdates = `-- name: ForkReportSecurityUpdates :many
SELECT hp.host_id, h.friendly_name, p.name AS package_name, hp.current_version, hp.available_version
FROM host_packages hp JOIN packages p ON p.id = hp.package_id JOIN hosts h ON h.id = hp.host_id
WHERE hp.host_id = ANY($1::text[])
  AND hp.needs_update = true AND hp.is_security_update = true
  AND NOT ($2::boolean AND fork_is_definition_update(hp.wua_categories, hp.wua_kb))
ORDER BY h.friendly_name, hp.host_id, p.name
`

type ForkReportSecurityUpdatesParams struct {
	HostIds                 []string `json:"host_ids"`
	IgnoreDefinitionUpdates bool     `json:"ignore_definition_updates"`
}

type ForkReportSecurityUpdatesRow struct {
	HostID           string  `json:"host_id"`
	FriendlyName     string  `json:"friendly_name"`
	PackageName      string  `json:"package_name"`
	CurrentVersion   string  `json:"current_version"`
	AvailableVersion *string `json:"available_version"`
}

// Available version ONLY from host_packages; packages.latest_version is a
// shared catalog that any host may overwrite.
func (q *Queries) ForkReportSecurityUpdates(ctx context.Context, arg ForkReportSecurityUpdatesParams) ([]ForkReportSecurityUpdatesRow, error) {
	rows, err := q.db.Query(ctx, forkReportSecurityUpdates, arg.HostIds, arg.IgnoreDefinitionUpdates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForkReportSecurityUpdatesRow
	for rows.Next() {
		var i ForkReportSecurityUpdatesRow
		if err := rows.Scan(
			&i.HostID,
			&i.FriendlyName,
			&i.PackageName,
			&i.CurrentVersion,
			&i.AvailableVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
