// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hosts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHosts = `-- name: CountHosts :one
SELECT COUNT(*) FROM hosts WHERE status = 'active'
`

func (q *Queries) CountHosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countHosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnscannedHosts = `-- name: CountUnscannedHosts :one
SELECT COUNT(*) FROM hosts h
WHERE NOT EXISTS (SELECT 1 FROM compliance_scans cs WHERE cs.host_id = h.id)
`

func (q *Queries) CountUnscannedHosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnscannedHosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHost = `-- name: CreateHost :exec
INSERT INTO hosts (
    id, machine_id, friendly_name, ip, os_type, os_version, architecture, last_update, status,
    api_id, api_key, agent_version, auto_update, created_at, updated_at,
    docker_enabled, compliance_enabled, compliance_on_demand_only, expected_platform
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19
)
`

type CreateHostParams struct {
	ID                     string           `json:"id"`
	MachineID              *string          `json:"machine_id"`
	FriendlyName           string           `json:"friendly_name"`
	Ip                     *string          `json:"ip"`
	OsType                 string           `json:"os_type"`
	OsVersion              string           `json:"os_version"`
	Architecture           *string          `json:"architecture"`
	LastUpdate             pgtype.Timestamp `json:"last_update"`
	Status                 string           `json:"status"`
	ApiID                  string           `json:"api_id"`
	ApiKey                 string           `json:"api_key"`
	AgentVersion           *string          `json:"agent_version"`
	AutoUpdate             bool             `json:"auto_update"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	DockerEnabled          bool             `json:"docker_enabled"`
	ComplianceEnabled      bool             `json:"compliance_enabled"`
	ComplianceOnDemandOnly bool             `json:"compliance_on_demand_only"`
	ExpectedPlatform       *string          `json:"expected_platform"`
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) error {
	_, err := q.db.Exec(ctx, createHost,
		arg.ID,
		arg.MachineID,
		arg.FriendlyName,
		arg.Ip,
		arg.OsType,
		arg.OsVersion,
		arg.Architecture,
		arg.LastUpdate,
		arg.Status,
		arg.ApiID,
		arg.ApiKey,
		arg.AgentVersion,
		arg.AutoUpdate,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DockerEnabled,
		arg.ComplianceEnabled,
		arg.ComplianceOnDemandOnly,
		arg.ExpectedPlatform,
	)
	return err
}

const deleteHost = `-- name: DeleteHost :exec
DELETE FROM hosts WHERE id = $1
`

func (q *Queries) DeleteHost(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteHost, id)
	return err
}

const deleteHostsByIDs = `-- name: DeleteHostsByIDs :exec
DELETE FROM hosts WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteHostsByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteHostsByIDs, dollar_1)
	return err
}

const getHostByApiID = `-- name: GetHostByApiID :one
SELECT id, machine_id, friendly_name, ip, os_type, os_version, architecture, last_update, status, created_at, updated_at, api_id, api_key, agent_version, auto_update, cpu_cores, cpu_model, disk_details, dns_servers, gateway_ip, hostname, kernel_version, installed_kernel_version, load_average, network_interfaces, ram_installed, selinux_status, swap_size, system_uptime, notes, needs_reboot, reboot_reason, allow_reboot, docker_enabled, compliance_enabled, compliance_on_demand_only, compliance_openscap_enabled, compliance_docker_bench_enabled, compliance_scanner_status, compliance_scanner_updated_at, compliance_default_profile_id, host_down_alerts_enabled, expected_platform, package_manager, primary_interface, awaiting_post_patch_report_run_id FROM hosts WHERE api_id = $1
`

func (q *Queries) GetHostByApiID(ctx context.Context, apiID string) (Host, error) {
	row := q.db.QueryRow(ctx, getHostByApiID, apiID)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.FriendlyName,
		&i.Ip,
		&i.OsType,
		&i.OsVersion,
		&i.Architecture,
		&i.LastUpdate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiID,
		&i.ApiKey,
		&i.AgentVersion,
		&i.AutoUpdate,
		&i.CpuCores,
		&i.CpuModel,
		&i.DiskDetails,
		&i.DnsServers,
		&i.GatewayIp,
		&i.Hostname,
		&i.KernelVersion,
		&i.InstalledKernelVersion,
		&i.LoadAverage,
		&i.NetworkInterfaces,
		&i.RamInstalled,
		&i.SelinuxStatus,
		&i.SwapSize,
		&i.SystemUptime,
		&i.Notes,
		&i.NeedsReboot,
		&i.RebootReason,
		&i.AllowReboot,
		&i.DockerEnabled,
		&i.ComplianceEnabled,
		&i.ComplianceOnDemandOnly,
		&i.ComplianceOpenscapEnabled,
		&i.ComplianceDockerBenchEnabled,
		&i.ComplianceScannerStatus,
		&i.ComplianceScannerUpdatedAt,
		&i.ComplianceDefaultProfileID,
		&i.HostDownAlertsEnabled,
		&i.ExpectedPlatform,
		&i.PackageManager,
		&i.PrimaryInterface,
		&i.AwaitingPostPatchReportRunID,
	)
	return i, err
}

const getHostByID = `-- name: GetHostByID :one
SELECT id, machine_id, friendly_name, ip, os_type, os_version, architecture, last_update, status, created_at, updated_at, api_id, api_key, agent_version, auto_update, cpu_cores, cpu_model, disk_details, dns_servers, gateway_ip, hostname, kernel_version, installed_kernel_version, load_average, network_interfaces, ram_installed, selinux_status, swap_size, system_uptime, notes, needs_reboot, reboot_reason, allow_reboot, docker_enabled, compliance_enabled, compliance_on_demand_only, compliance_openscap_enabled, compliance_docker_bench_enabled, compliance_scanner_status, compliance_scanner_updated_at, compliance_default_profile_id, host_down_alerts_enabled, expected_platform, package_manager, primary_interface, awaiting_post_patch_report_run_id FROM hosts WHERE id = $1
`

func (q *Queries) GetHostByID(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRow(ctx, getHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.FriendlyName,
		&i.Ip,
		&i.OsType,
		&i.OsVersion,
		&i.Architecture,
		&i.LastUpdate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiID,
		&i.ApiKey,
		&i.AgentVersion,
		&i.AutoUpdate,
		&i.CpuCores,
		&i.CpuModel,
		&i.DiskDetails,
		&i.DnsServers,
		&i.GatewayIp,
		&i.Hostname,
		&i.KernelVersion,
		&i.InstalledKernelVersion,
		&i.LoadAverage,
		&i.NetworkInterfaces,
		&i.RamInstalled,
		&i.SelinuxStatus,
		&i.SwapSize,
		&i.SystemUptime,
		&i.Notes,
		&i.NeedsReboot,
		&i.RebootReason,
		&i.AllowReboot,
		&i.DockerEnabled,
		&i.ComplianceEnabled,
		&i.ComplianceOnDemandOnly,
		&i.ComplianceOpenscapEnabled,
		&i.ComplianceDockerBenchEnabled,
		&i.ComplianceScannerStatus,
		&i.ComplianceScannerUpdatedAt,
		&i.ComplianceDefaultProfileID,
		&i.HostDownAlertsEnabled,
		&i.ExpectedPlatform,
		&i.PackageManager,
		&i.PrimaryInterface,
		&i.AwaitingPostPatchReportRunID,
	)
	return i, err
}

const getHostsByIDs = `-- name: GetHostsByIDs :many
SELECT id, machine_id, friendly_name, ip, os_type, os_version, architecture, last_update, status, created_at, updated_at, api_id, api_key, agent_version, auto_update, cpu_cores, cpu_model, disk_details, dns_servers, gateway_ip, hostname, kernel_version, installed_kernel_version, load_average, network_interfaces, ram_installed, selinux_status, swap_size, system_uptime, notes, needs_reboot, reboot_reason, allow_reboot, docker_enabled, compliance_enabled, compliance_on_demand_only, compliance_openscap_enabled, compliance_docker_bench_enabled, compliance_scanner_status, compliance_scanner_updated_at, compliance_default_profile_id, host_down_alerts_enabled, expected_platform, package_manager, primary_interface, awaiting_post_patch_report_run_id FROM hosts WHERE id = ANY($1::text[])
`

func (q *Queries) GetHostsByIDs(ctx context.Context, dollar_1 []string) ([]Host, error) {
	rows, err := q.db.Query(ctx, getHostsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.FriendlyName,
			&i.Ip,
			&i.OsType,
			&i.OsVersion,
			&i.Architecture,
			&i.LastUpdate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApiID,
			&i.ApiKey,
			&i.AgentVersion,
			&i.AutoUpdate,
			&i.CpuCores,
			&i.CpuModel,
			&i.DiskDetails,
			&i.DnsServers,
			&i.GatewayIp,
			&i.Hostname,
			&i.KernelVersion,
			&i.InstalledKernelVersion,
			&i.LoadAverage,
			&i.NetworkInterfaces,
			&i.RamInstalled,
			&i.SelinuxStatus,
			&i.SwapSize,
			&i.SystemUptime,
			&i.Notes,
			&i.NeedsReboot,
			&i.RebootReason,
			&i.AllowReboot,
			&i.DockerEnabled,
			&i.ComplianceEnabled,
			&i.ComplianceOnDemandOnly,
			&i.ComplianceOpenscapEnabled,
			&i.ComplianceDockerBenchEnabled,
			&i.ComplianceScannerStatus,
			&i.ComplianceScannerUpdatedAt,
			&i.ComplianceDefaultProfileID,
			&i.HostDownAlertsEnabled,
			&i.ExpectedPlatform,
			&i.PackageManager,
			&i.PrimaryInterface,
			&i.AwaitingPostPatchReportRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHosts = `-- name: ListHosts :many
SELECT id, machine_id, friendly_name, ip, os_type, os_version, architecture, last_update, status, created_at, updated_at, api_id, api_key, agent_version, auto_update, cpu_cores, cpu_model, disk_details, dns_servers, gateway_ip, hostname, kernel_version, installed_kernel_version, load_average, network_interfaces, ram_installed, selinux_status, swap_size, system_uptime, notes, needs_reboot, reboot_reason, allow_reboot, docker_enabled, compliance_enabled, compliance_on_demand_only, compliance_openscap_enabled, compliance_docker_bench_enabled, compliance_scanner_status, compliance_scanner_updated_at, compliance_default_profile_id, host_down_alerts_enabled, expected_platform, package_manager, primary_interface, awaiting_post_patch_report_run_id FROM hosts ORDER BY friendly_name
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.FriendlyName,
			&i.Ip,
			&i.OsType,
			&i.OsVersion,
			&i.Architecture,
			&i.LastUpdate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApiID,
			&i.ApiKey,
			&i.AgentVersion,
			&i.AutoUpdate,
			&i.CpuCores,
			&i.CpuModel,
			&i.DiskDetails,
			&i.DnsServers,
			&i.GatewayIp,
			&i.Hostname,
			&i.KernelVersion,
			&i.InstalledKernelVersion,
			&i.LoadAverage,
			&i.NetworkInterfaces,
			&i.RamInstalled,
			&i.SelinuxStatus,
			&i.SwapSize,
			&i.SystemUptime,
			&i.Notes,
			&i.NeedsReboot,
			&i.RebootReason,
			&i.AllowReboot,
			&i.DockerEnabled,
			&i.ComplianceEnabled,
			&i.ComplianceOnDemandOnly,
			&i.ComplianceOpenscapEnabled,
			&i.ComplianceDockerBenchEnabled,
			&i.ComplianceScannerStatus,
			&i.ComplianceScannerUpdatedAt,
			&i.ComplianceDefaultProfileID,
			&i.HostDownAlertsEnabled,
			&i.ExpectedPlatform,
			&i.PackageManager,
			&i.PrimaryInterface,
			&i.AwaitingPostPatchReportRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsForComplianceDashboard = `-- name: ListHostsForComplianceDashboard :many
SELECT id, hostname, friendly_name, compliance_enabled, compliance_on_demand_only, docker_enabled
FROM hosts
`

type ListHostsForComplianceDashboardRow struct {
	ID                     string  `json:"id"`
	Hostname               *string `json:"hostname"`
	FriendlyName           string  `json:"friendly_name"`
	ComplianceEnabled      bool    `json:"compliance_enabled"`
	ComplianceOnDemandOnly bool    `json:"compliance_on_demand_only"`
	DockerEnabled          bool    `json:"docker_enabled"`
}

func (q *Queries) ListHostsForComplianceDashboard(ctx context.Context) ([]ListHostsForComplianceDashboardRow, error) {
	rows, err := q.db.Query(ctx, listHostsForComplianceDashboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHostsForComplianceDashboardRow
	for rows.Next() {
		var i ListHostsForComplianceDashboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.FriendlyName,
			&i.ComplianceEnabled,
			&i.ComplianceOnDemandOnly,
			&i.DockerEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsPaginated = `-- name: ListHostsPaginated :many
SELECT id, friendly_name, hostname, ip, os_type, os_version, architecture, last_update, status, api_id, agent_version, auto_update, created_at, notes, system_uptime, needs_reboot, allow_reboot, docker_enabled, compliance_enabled
FROM hosts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListHostsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListHostsPaginatedRow struct {
	ID                string           `json:"id"`
	FriendlyName      string           `json:"friendly_name"`
	Hostname          *string          `json:"hostname"`
	Ip                *string          `json:"ip"`
	OsType            string           `json:"os_type"`
	OsVersion         string           `json:"os_version"`
	Architecture      *string          `json:"architecture"`
	LastUpdate        pgtype.Timestamp `json:"last_update"`
	Status            string           `json:"status"`
	ApiID             string           `json:"api_id"`
	AgentVersion      *string          `json:"agent_version"`
	AutoUpdate        bool             `json:"auto_update"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	Notes             *string          `json:"notes"`
	SystemUptime      *string          `json:"system_uptime"`
	NeedsReboot       *bool            `json:"needs_reboot"`
	AllowReboot       bool             `json:"allow_reboot"`
	DockerEnabled     bool             `json:"docker_enabled"`
	ComplianceEnabled bool             `json:"compliance_enabled"`
}

func (q *Queries) ListHostsPaginated(ctx context.Context, arg ListHostsPaginatedParams) ([]ListHostsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listHostsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHostsPaginatedRow
	for rows.Next() {
		var i ListHostsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendlyName,
			&i.Hostname,
			&i.Ip,
			&i.OsType,
			&i.OsVersion,
			&i.Architecture,
			&i.LastUpdate,
			&i.Status,
			&i.ApiID,
			&i.AgentVersion,
			&i.AutoUpdate,
			&i.CreatedAt,
			&i.Notes,
			&i.SystemUptime,
			&i.NeedsReboot,
			&i.AllowReboot,
			&i.DockerEnabled,
			&i.ComplianceEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHostAwaitingPostPatchReport = `-- name: SetHostAwaitingPostPatchReport :exec
UPDATE hosts SET awaiting_post_patch_report_run_id = $1, updated_at = NOW() WHERE id = $2
`

type SetHostAwaitingPostPatchReportParams struct {
	AwaitingPostPatchReportRunID *string `json:"awaiting_post_patch_report_run_id"`
	ID                           string  `json:"id"`
}

func (q *Queries) SetHostAwaitingPostPatchReport(ctx context.Context, arg SetHostAwaitingPostPatchReportParams) error {
	_, err := q.db.Exec(ctx, setHostAwaitingPostPatchReport, arg.AwaitingPostPatchReportRunID, arg.ID)
	return err
}

const updateHostApiCredentials = `-- name: UpdateHostApiCredentials :exec
UPDATE hosts SET api_id = $1, api_key = $2, updated_at = NOW() WHERE id = $3
`

type UpdateHostApiCredentialsParams struct {
	ApiID  string `json:"api_id"`
	ApiKey string `json:"api_key"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateHostApiCredentials(ctx context.Context, arg UpdateHostApiCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateHostApiCredentials, arg.ApiID, arg.ApiKey, arg.ID)
	return err
}

const updateHostAutoUpdate = `-- name: UpdateHostAutoUpdate :exec
UPDATE hosts SET auto_update = $1, updated_at = NOW() WHERE id = $2
`

type UpdateHostAutoUpdateParams struct {
	AutoUpdate bool   `json:"auto_update"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateHostAutoUpdate(ctx context.Context, arg UpdateHostAutoUpdateParams) error {
	_, err := q.db.Exec(ctx, updateHostAutoUpdate, arg.AutoUpdate, arg.ID)
	return err
}

const updateHostComplianceDefaultProfile = `-- name: UpdateHostComplianceDefaultProfile :exec
UPDATE hosts SET compliance_default_profile_id = $1, updated_at = NOW() WHERE id = $2
`

type UpdateHostComplianceDefaultProfileParams struct {
	ComplianceDefaultProfileID *string `json:"compliance_default_profile_id"`
	ID                         string  `json:"id"`
}

func (q *Queries) UpdateHostComplianceDefaultProfile(ctx context.Context, arg UpdateHostComplianceDefaultProfileParams) error {
	_, err := q.db.Exec(ctx, updateHostComplianceDefaultProfile, arg.ComplianceDefaultProfileID, arg.ID)
	return err
}

const updateHostComplianceEnabled = `-- name: UpdateHostComplianceEnabled :exec
UPDATE hosts SET compliance_enabled = $1, updated_at = NOW() WHERE id = $2
`

type UpdateHostComplianceEnabledParams struct {
	ComplianceEnabled bool   `json:"compliance_enabled"`
	ID                string `json:"id"`
}

func (q *Queries) UpdateHostComplianceEnabled(ctx context.Context, arg UpdateHostComplianceEnabledParams) error {
	_, err := q.db.Exec(ctx, updateHostComplianceEnabled, arg.ComplianceEnabled, arg.ID)
	return err
}

const updateHostComplianceMode = `-- name: UpdateHostComplianceMode :exec
UPDATE hosts SET compliance_enabled = $1, compliance_on_demand_only = $2, updated_at = NOW() WHERE id = $3
`

type UpdateHostComplianceModeParams struct {
	ComplianceEnabled      bool   `json:"compliance_enabled"`
	ComplianceOnDemandOnly bool   `json:"compliance_on_demand_only"`
	ID                     string `json:"id"`
}

func (q *Queries) UpdateHostComplianceMode(ctx context.Context, arg UpdateHostComplianceModeParams) error {
	_, err := q.db.Exec(ctx, updateHostComplianceMode, arg.ComplianceEnabled, arg.ComplianceOnDemandOnly, arg.ID)
	return err
}

const updateHostComplianceScannerStatus = `-- name: UpdateHostComplianceScannerStatus :exec
UPDATE hosts SET compliance_scanner_status = $1, compliance_scanner_updated_at = $2, updated_at = NOW() WHERE id = $3
`

type UpdateHostComplianceScannerStatusParams struct {
	ComplianceScannerStatus    []byte           `json:"compliance_scanner_status"`
	ComplianceScannerUpdatedAt pgtype.Timestamp `json:"compliance_scanner_updated_at"`
	ID                         string           `json:"id"`
}

func (q *Queries) UpdateHostComplianceScannerStatus(ctx context.Context, arg UpdateHostComplianceScannerStatusParams) error {
	_, err := q.db.Exec(ctx, updateHostComplianceScannerStatus, arg.ComplianceScannerStatus, arg.ComplianceScannerUpdatedAt, arg.ID)
	return err
}

const updateHostComplianceScanners = `-- name: UpdateHostComplianceScanners :exec
UPDATE hosts SET compliance_openscap_enabled = $1, compliance_docker_bench_enabled = $2, updated_at = NOW() WHERE id = $3
`

type UpdateHostComplianceScannersParams struct {
	ComplianceOpenscapEnabled    bool   `json:"compliance_openscap_enabled"`
	ComplianceDockerBenchEnabled bool   `json:"compliance_docker_bench_enabled"`
	ID                           string `json:"id"`
}

func (q *Queries) UpdateHostComplianceScanners(ctx context.Context, arg UpdateHostComplianceScannersParams) error {
	_, err := q.db.Exec(ctx, updateHostComplianceScanners, arg.ComplianceOpenscapEnabled, arg.ComplianceDockerBenchEnabled, arg.ID)
	return err
}

const updateHostConnection = `-- name: UpdateHostConnection :exec
UPDATE hosts SET ip = $1, hostname = $2, updated_at = NOW() WHERE id = $3
`

type UpdateHostConnectionParams struct {
	Ip       *string `json:"ip"`
	Hostname *string `json:"hostname"`
	ID       string  `json:"id"`
}

func (q *Queries) UpdateHostConnection(ctx context.Context, arg UpdateHostConnectionParams) error {
	_, err := q.db.Exec(ctx, updateHostConnection, arg.Ip, arg.Hostname, arg.ID)
	return err
}

const updateHostDockerEnabled = `-- name: UpdateHostDockerEnabled :exec
UPDATE hosts SET docker_enabled = $1, updated_at = NOW() WHERE id = $2
`

type UpdateHostDockerEnabledParams struct {
	DockerEnabled bool   `json:"docker_enabled"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateHostDockerEnabled(ctx context.Context, arg UpdateHostDockerEnabledParams) error {
	_, err := q.db.Exec(ctx, updateHostDockerEnabled, arg.DockerEnabled, arg.ID)
	return err
}

const updateHostDownAlerts = `-- name: UpdateHostDownAlerts :exec
UPDATE hosts SET host_down_alerts_enabled = $1, updated_at = NOW() WHERE id = $2
`

type UpdateHostDownAlertsParams struct {
	HostDownAlertsEnabled *bool  `json:"host_down_alerts_enabled"`
	ID                    string `json:"id"`
}

func (q *Queries) UpdateHostDownAlerts(ctx context.Context, arg UpdateHostDownAlertsParams) error {
	_, err := q.db.Exec(ctx, updateHostDownAlerts, arg.HostDownAlertsEnabled, arg.ID)
	return err
}

const updateHostFriendlyName = `-- name: UpdateHostFriendlyName :exec
UPDATE hosts SET friendly_name = $1, updated_at = NOW() WHERE id = $2
`

type UpdateHostFriendlyNameParams struct {
	FriendlyName string `json:"friendly_name"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateHostFriendlyName(ctx context.Context, arg UpdateHostFriendlyNameParams) error {
	_, err := q.db.Exec(ctx, updateHostFriendlyName, arg.FriendlyName, arg.ID)
	return err
}

const updateHostNotes = `-- name: UpdateHostNotes :exec
UPDATE hosts SET notes = $1, updated_at = NOW() WHERE id = $2
`

type UpdateHostNotesParams struct {
	Notes *string `json:"notes"`
	ID    string  `json:"id"`
}

func (q *Queries) UpdateHostNotes(ctx context.Context, arg UpdateHostNotesParams) error {
	_, err := q.db.Exec(ctx, updateHostNotes, arg.Notes, arg.ID)
	return err
}

const updateHostPing = `-- name: UpdateHostPing :exec
UPDATE hosts SET last_update = NOW(), updated_at = NOW(), status = 'active' WHERE id = $1
`

func (q *Queries) UpdateHostPing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateHostPing, id)
	return err
}

const updateHostPrimaryInterface = `-- name: UpdateHostPrimaryInterface :exec
UPDATE hosts SET primary_interface = $1, updated_at = NOW() WHERE id = $2
`

type UpdateHostPrimaryInterfaceParams struct {
	PrimaryInterface *string `json:"primary_interface"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateHostPrimaryInterface(ctx context.Context, arg UpdateHostPrimaryInterfaceParams) error {
	_, err := q.db.Exec(ctx, updateHostPrimaryInterface, arg.PrimaryInterface, arg.ID)
	return err
}

const updateHostRebootStatus = `-- name: UpdateHostRebootStatus :exec
UPDATE hosts SET needs_reboot = $2, reboot_reason = $3, updated_at = NOW() WHERE id = $1
`

type UpdateHostRebootStatusParams struct {
	ID           string  `json:"id"`
	NeedsReboot  *bool   `json:"needs_reboot"`
	RebootReason *string `json:"reboot_reason"`
}

func (q *Queries) UpdateHostRebootStatus(ctx context.Context, arg UpdateHostRebootStatusParams) error {
	_, err := q.db.Exec(ctx, updateHostRebootStatus, arg.ID, arg.NeedsReboot, arg.RebootReason)
	return err
}

const updateHostsAllowReboot = `-- name: UpdateHostsAllowReboot :exec
UPDATE hosts SET allow_reboot = $1, updated_at = NOW() WHERE id = ANY($2::text[])
`

type UpdateHostsAllowRebootParams struct {
	AllowReboot bool     `json:"allow_reboot"`
	Ids         []string `json:"ids"`
}

func (q *Queries) UpdateHostsAllowReboot(ctx context.Context, arg UpdateHostsAllowRebootParams) error {
	_, err := q.db.Exec(ctx, updateHostsAllowReboot, arg.AllowReboot, arg.Ids)
	return err
}
