// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationDestination = `-- name: CreateNotificationDestination :one
INSERT INTO notification_destinations (id, channel_type, display_name, config_encrypted, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, channel_type, display_name, config_encrypted, enabled, created_at, updated_at
`

type CreateNotificationDestinationParams struct {
	ID              string `json:"id"`
	ChannelType     string `json:"channel_type"`
	DisplayName     string `json:"display_name"`
	ConfigEncrypted string `json:"config_encrypted"`
	Enabled         bool   `json:"enabled"`
}

func (q *Queries) CreateNotificationDestination(ctx context.Context, arg CreateNotificationDestinationParams) (NotificationDestination, error) {
	row := q.db.QueryRow(ctx, createNotificationDestination,
		arg.ID,
		arg.ChannelType,
		arg.DisplayName,
		arg.ConfigEncrypted,
		arg.Enabled,
	)
	var i NotificationDestination
	err := row.Scan(
		&i.ID,
		&i.ChannelType,
		&i.DisplayName,
		&i.ConfigEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotificationRoute = `-- name: CreateNotificationRoute :one
INSERT INTO notification_routes (id, destination_id, event_types, min_severity, host_group_ids, host_ids, match_rules, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, destination_id, event_types, min_severity, host_group_ids, host_ids, match_rules, enabled, created_at, updated_at
`

type CreateNotificationRouteParams struct {
	ID            string `json:"id"`
	DestinationID string `json:"destination_id"`
	EventTypes    []byte `json:"event_types"`
	MinSeverity   string `json:"min_severity"`
	HostGroupIds  []byte `json:"host_group_ids"`
	HostIds       []byte `json:"host_ids"`
	MatchRules    []byte `json:"match_rules"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) CreateNotificationRoute(ctx context.Context, arg CreateNotificationRouteParams) (NotificationRoute, error) {
	row := q.db.QueryRow(ctx, createNotificationRoute,
		arg.ID,
		arg.DestinationID,
		arg.EventTypes,
		arg.MinSeverity,
		arg.HostGroupIds,
		arg.HostIds,
		arg.MatchRules,
		arg.Enabled,
	)
	var i NotificationRoute
	err := row.Scan(
		&i.ID,
		&i.DestinationID,
		&i.EventTypes,
		&i.MinSeverity,
		&i.HostGroupIds,
		&i.HostIds,
		&i.MatchRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScheduledReport = `-- name: CreateScheduledReport :one
INSERT INTO scheduled_reports (id, name, cron_expr, enabled, definition, destination_ids, timezone, next_run_at, last_run_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
RETURNING id, name, cron_expr, enabled, definition, destination_ids, timezone, next_run_at, last_run_at, created_at, updated_at, fork_email_recipients
`

type CreateScheduledReportParams struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	CronExpr       string           `json:"cron_expr"`
	Enabled        bool             `json:"enabled"`
	Definition     []byte           `json:"definition"`
	DestinationIds []byte           `json:"destination_ids"`
	Timezone       string           `json:"timezone"`
	NextRunAt      pgtype.Timestamp `json:"next_run_at"`
	LastRunAt      pgtype.Timestamp `json:"last_run_at"`
}

func (q *Queries) CreateScheduledReport(ctx context.Context, arg CreateScheduledReportParams) (ScheduledReport, error) {
	row := q.db.QueryRow(ctx, createScheduledReport,
		arg.ID,
		arg.Name,
		arg.CronExpr,
		arg.Enabled,
		arg.Definition,
		arg.DestinationIds,
		arg.Timezone,
		arg.NextRunAt,
		arg.LastRunAt,
	)
	var i ScheduledReport
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpr,
		&i.Enabled,
		&i.Definition,
		&i.DestinationIds,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForkEmailRecipients,
	)
	return i, err
}

const deleteNotificationDestination = `-- name: DeleteNotificationDestination :exec
DELETE FROM notification_destinations WHERE id = $1
`

func (q *Queries) DeleteNotificationDestination(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNotificationDestination, id)
	return err
}

const deleteNotificationRoute = `-- name: DeleteNotificationRoute :exec
DELETE FROM notification_routes WHERE id = $1
`

func (q *Queries) DeleteNotificationRoute(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNotificationRoute, id)
	return err
}

const deleteScheduledReport = `-- name: DeleteScheduledReport :exec
DELETE FROM scheduled_reports WHERE id = $1
`

func (q *Queries) DeleteScheduledReport(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteScheduledReport, id)
	return err
}

const getNotificationDestinationByID = `-- name: GetNotificationDestinationByID :one
SELECT id, channel_type, display_name, config_encrypted, enabled, created_at, updated_at FROM notification_destinations WHERE id = $1
`

func (q *Queries) GetNotificationDestinationByID(ctx context.Context, id string) (NotificationDestination, error) {
	row := q.db.QueryRow(ctx, getNotificationDestinationByID, id)
	var i NotificationDestination
	err := row.Scan(
		&i.ID,
		&i.ChannelType,
		&i.DisplayName,
		&i.ConfigEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationRouteByID = `-- name: GetNotificationRouteByID :one
SELECT id, destination_id, event_types, min_severity, host_group_ids, host_ids, match_rules, enabled, created_at, updated_at FROM notification_routes WHERE id = $1
`

func (q *Queries) GetNotificationRouteByID(ctx context.Context, id string) (NotificationRoute, error) {
	row := q.db.QueryRow(ctx, getNotificationRouteByID, id)
	var i NotificationRoute
	err := row.Scan(
		&i.ID,
		&i.DestinationID,
		&i.EventTypes,
		&i.MinSeverity,
		&i.HostGroupIds,
		&i.HostIds,
		&i.MatchRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduledReportByID = `-- name: GetScheduledReportByID :one
SELECT id, name, cron_expr, enabled, definition, destination_ids, timezone, next_run_at, last_run_at, created_at, updated_at, fork_email_recipients FROM scheduled_reports WHERE id = $1
`

func (q *Queries) GetScheduledReportByID(ctx context.Context, id string) (ScheduledReport, error) {
	row := q.db.QueryRow(ctx, getScheduledReportByID, id)
	var i ScheduledReport
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpr,
		&i.Enabled,
		&i.Definition,
		&i.DestinationIds,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForkEmailRecipients,
	)
	return i, err
}

const insertNotificationDeliveryLog = `-- name: InsertNotificationDeliveryLog :one
INSERT INTO notification_delivery_log (
    id, event_fingerprint, reference_type, reference_id, destination_id, event_type, status, error_message, attempt_count, provider_message_id, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
RETURNING id, event_fingerprint, reference_type, reference_id, destination_id, event_type, status, error_message, attempt_count, provider_message_id, created_at, updated_at
`

type InsertNotificationDeliveryLogParams struct {
	ID                string  `json:"id"`
	EventFingerprint  string  `json:"event_fingerprint"`
	ReferenceType     string  `json:"reference_type"`
	ReferenceID       string  `json:"reference_id"`
	DestinationID     string  `json:"destination_id"`
	EventType         string  `json:"event_type"`
	Status            string  `json:"status"`
	ErrorMessage      *string `json:"error_message"`
	AttemptCount      int32   `json:"attempt_count"`
	ProviderMessageID *string `json:"provider_message_id"`
}

func (q *Queries) InsertNotificationDeliveryLog(ctx context.Context, arg InsertNotificationDeliveryLogParams) (NotificationDeliveryLog, error) {
	row := q.db.QueryRow(ctx, insertNotificationDeliveryLog,
		arg.ID,
		arg.EventFingerprint,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.DestinationID,
		arg.EventType,
		arg.Status,
		arg.ErrorMessage,
		arg.AttemptCount,
		arg.ProviderMessageID,
	)
	var i NotificationDeliveryLog
	err := row.Scan(
		&i.ID,
		&i.EventFingerprint,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.DestinationID,
		&i.EventType,
		&i.Status,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.ProviderMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScheduledReportRun = `-- name: InsertScheduledReportRun :one
INSERT INTO scheduled_report_runs (id, scheduled_report_id, run_at, status, error_message, summary_hash, created_at)
VALUES ($1, $2, NOW(), $3, $4, $5, NOW())
RETURNING id, scheduled_report_id, run_at, status, error_message, summary_hash, created_at
`

type InsertScheduledReportRunParams struct {
	ID                string  `json:"id"`
	ScheduledReportID string  `json:"scheduled_report_id"`
	Status            string  `json:"status"`
	ErrorMessage      *string `json:"error_message"`
	SummaryHash       *string `json:"summary_hash"`
}

func (q *Queries) InsertScheduledReportRun(ctx context.Context, arg InsertScheduledReportRunParams) (ScheduledReportRun, error) {
	row := q.db.QueryRow(ctx, insertScheduledReportRun,
		arg.ID,
		arg.ScheduledReportID,
		arg.Status,
		arg.ErrorMessage,
		arg.SummaryHash,
	)
	var i ScheduledReportRun
	err := row.Scan(
		&i.ID,
		&i.ScheduledReportID,
		&i.RunAt,
		&i.Status,
		&i.ErrorMessage,
		&i.SummaryHash,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationDeliveryLog = `-- name: ListNotificationDeliveryLog :many
SELECT id, event_fingerprint, reference_type, reference_id, destination_id, event_type, status, error_message, attempt_count, provider_message_id, created_at, updated_at FROM notification_delivery_log ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListNotificationDeliveryLogParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNotificationDeliveryLog(ctx context.Context, arg ListNotificationDeliveryLogParams) ([]NotificationDeliveryLog, error) {
	rows, err := q.db.Query(ctx, listNotificationDeliveryLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDeliveryLog
	for rows.Next() {
		var i NotificationDeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.EventFingerprint,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.DestinationID,
			&i.EventType,
			&i.Status,
			&i.ErrorMessage,
			&i.AttemptCount,
			&i.ProviderMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDestinations = `-- name: ListNotificationDestinations :many
SELECT id, channel_type, display_name, config_encrypted, enabled, created_at, updated_at FROM notification_destinations ORDER BY display_name
`

func (q *Queries) ListNotificationDestinations(ctx context.Context) ([]NotificationDestination, error) {
	rows, err := q.db.Query(ctx, listNotificationDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDestination
	for rows.Next() {
		var i NotificationDestination
		if err := rows.Scan(
			&i.ID,
			&i.ChannelType,
			&i.DisplayName,
			&i.ConfigEncrypted,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationRoutes = `-- name: ListNotificationRoutes :many
SELECT
    r.id, r.destination_id, r.event_types, r.min_severity, r.host_group_ids, r.host_ids, r.match_rules, r.enabled AS route_enabled,
    r.created_at, r.updated_at,
    d.channel_type, d.display_name AS destination_display_name
FROM notification_routes r
JOIN notification_destinations d ON d.id = r.destination_id
ORDER BY d.display_name
`

type ListNotificationRoutesRow struct {
	ID                     string           `json:"id"`
	DestinationID          string           `json:"destination_id"`
	EventTypes             []byte           `json:"event_types"`
	MinSeverity            string           `json:"min_severity"`
	HostGroupIds           []byte           `json:"host_group_ids"`
	HostIds                []byte           `json:"host_ids"`
	MatchRules             []byte           `json:"match_rules"`
	RouteEnabled           bool             `json:"route_enabled"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	ChannelType            string           `json:"channel_type"`
	DestinationDisplayName string           `json:"destination_display_name"`
}

func (q *Queries) ListNotificationRoutes(ctx context.Context) ([]ListNotificationRoutesRow, error) {
	rows, err := q.db.Query(ctx, listNotificationRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationRoutesRow
	for rows.Next() {
		var i ListNotificationRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.DestinationID,
			&i.EventTypes,
			&i.MinSeverity,
			&i.HostGroupIds,
			&i.HostIds,
			&i.MatchRules,
			&i.RouteEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.DestinationDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationRoutesForEvent = `-- name: ListNotificationRoutesForEvent :many
SELECT
    r.id, r.destination_id, r.event_types, r.min_severity, r.host_group_ids, r.host_ids, r.match_rules, r.enabled AS route_enabled,
    r.created_at, r.updated_at,
    d.channel_type, d.display_name AS destination_display_name, d.config_encrypted, d.enabled AS destination_enabled
FROM notification_routes r
JOIN notification_destinations d ON d.id = r.destination_id
WHERE r.enabled = true AND d.enabled = true
  AND (r.event_types @> to_jsonb($1::text) OR r.event_types @> '["*"]'::jsonb)
ORDER BY r.id
`

type ListNotificationRoutesForEventRow struct {
	ID                     string           `json:"id"`
	DestinationID          string           `json:"destination_id"`
	EventTypes             []byte           `json:"event_types"`
	MinSeverity            string           `json:"min_severity"`
	HostGroupIds           []byte           `json:"host_group_ids"`
	HostIds                []byte           `json:"host_ids"`
	MatchRules             []byte           `json:"match_rules"`
	RouteEnabled           bool             `json:"route_enabled"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	ChannelType            string           `json:"channel_type"`
	DestinationDisplayName string           `json:"destination_display_name"`
	ConfigEncrypted        string           `json:"config_encrypted"`
	DestinationEnabled     bool             `json:"destination_enabled"`
}

func (q *Queries) ListNotificationRoutesForEvent(ctx context.Context, dollar_1 string) ([]ListNotificationRoutesForEventRow, error) {
	rows, err := q.db.Query(ctx, listNotificationRoutesForEvent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationRoutesForEventRow
	for rows.Next() {
		var i ListNotificationRoutesForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.DestinationID,
			&i.EventTypes,
			&i.MinSeverity,
			&i.HostGroupIds,
			&i.HostIds,
			&i.MatchRules,
			&i.RouteEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.DestinationDisplayName,
			&i.ConfigEncrypted,
			&i.DestinationEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledReports = `-- name: ListScheduledReports :many
SELECT id, name, cron_expr, enabled, definition, destination_ids, timezone, next_run_at, last_run_at, created_at, updated_at, fork_email_recipients FROM scheduled_reports ORDER BY name
`

func (q *Queries) ListScheduledReports(ctx context.Context) ([]ScheduledReport, error) {
	rows, err := q.db.Query(ctx, listScheduledReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledReport
	for rows.Next() {
		var i ScheduledReport
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpr,
			&i.Enabled,
			&i.Definition,
			&i.DestinationIds,
			&i.Timezone,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ForkEmailRecipients,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledReportsDue = `-- name: ListScheduledReportsDue :many
SELECT id, name, cron_expr, enabled, definition, destination_ids, timezone, next_run_at, last_run_at, created_at, updated_at, fork_email_recipients FROM scheduled_reports
WHERE enabled = true AND (next_run_at IS NULL OR next_run_at <= $1)
ORDER BY next_run_at NULLS FIRST
`

func (q *Queries) ListScheduledReportsDue(ctx context.Context, nextRunAt pgtype.Timestamp) ([]ScheduledReport, error) {
	rows, err := q.db.Query(ctx, listScheduledReportsDue, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledReport
	for rows.Next() {
		var i ScheduledReport
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpr,
			&i.Enabled,
			&i.Definition,
			&i.DestinationIds,
			&i.Timezone,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ForkEmailRecipients,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationDestination = `-- name: UpdateNotificationDestination :one
UPDATE notification_destinations
SET display_name = $2, config_encrypted = $3, enabled = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, channel_type, display_name, config_encrypted, enabled, created_at, updated_at
`

type UpdateNotificationDestinationParams struct {
	ID              string `json:"id"`
	DisplayName     string `json:"display_name"`
	ConfigEncrypted string `json:"config_encrypted"`
	Enabled         bool   `json:"enabled"`
}

func (q *Queries) UpdateNotificationDestination(ctx context.Context, arg UpdateNotificationDestinationParams) (NotificationDestination, error) {
	row := q.db.QueryRow(ctx, updateNotificationDestination,
		arg.ID,
		arg.DisplayName,
		arg.ConfigEncrypted,
		arg.Enabled,
	)
	var i NotificationDestination
	err := row.Scan(
		&i.ID,
		&i.ChannelType,
		&i.DisplayName,
		&i.ConfigEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationRoute = `-- name: UpdateNotificationRoute :one
UPDATE notification_routes
SET destination_id = $2, event_types = $3, min_severity = $4, host_group_ids = $5, host_ids = $6, match_rules = $7, enabled = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, destination_id, event_types, min_severity, host_group_ids, host_ids, match_rules, enabled, created_at, updated_at
`

type UpdateNotificationRouteParams struct {
	ID            string `json:"id"`
	DestinationID string `json:"destination_id"`
	EventTypes    []byte `json:"event_types"`
	MinSeverity   string `json:"min_severity"`
	HostGroupIds  []byte `json:"host_group_ids"`
	HostIds       []byte `json:"host_ids"`
	MatchRules    []byte `json:"match_rules"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) UpdateNotificationRoute(ctx context.Context, arg UpdateNotificationRouteParams) (NotificationRoute, error) {
	row := q.db.QueryRow(ctx, updateNotificationRoute,
		arg.ID,
		arg.DestinationID,
		arg.EventTypes,
		arg.MinSeverity,
		arg.HostGroupIds,
		arg.HostIds,
		arg.MatchRules,
		arg.Enabled,
	)
	var i NotificationRoute
	err := row.Scan(
		&i.ID,
		&i.DestinationID,
		&i.EventTypes,
		&i.MinSeverity,
		&i.HostGroupIds,
		&i.HostIds,
		&i.MatchRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScheduledReport = `-- name: UpdateScheduledReport :one
UPDATE scheduled_reports
SET name = $2, cron_expr = $3, enabled = $4, definition = $5, destination_ids = $6, timezone = $7, next_run_at = $8, last_run_at = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, name, cron_expr, enabled, definition, destination_ids, timezone, next_run_at, last_run_at, created_at, updated_at, fork_email_recipients
`

type UpdateScheduledReportParams struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	CronExpr       string           `json:"cron_expr"`
	Enabled        bool             `json:"enabled"`
	Definition     []byte           `json:"definition"`
	DestinationIds []byte           `json:"destination_ids"`
	Timezone       string           `json:"timezone"`
	NextRunAt      pgtype.Timestamp `json:"next_run_at"`
	LastRunAt      pgtype.Timestamp `json:"last_run_at"`
}

func (q *Queries) UpdateScheduledReport(ctx context.Context, arg UpdateScheduledReportParams) (ScheduledReport, error) {
	row := q.db.QueryRow(ctx, updateScheduledReport,
		arg.ID,
		arg.Name,
		arg.CronExpr,
		arg.Enabled,
		arg.Definition,
		arg.DestinationIds,
		arg.Timezone,
		arg.NextRunAt,
		arg.LastRunAt,
	)
	var i ScheduledReport
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpr,
		&i.Enabled,
		&i.Definition,
		&i.DestinationIds,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForkEmailRecipients,
	)
	return i, err
}

const updateScheduledReportRunTimes = `-- name: UpdateScheduledReportRunTimes :exec
UPDATE scheduled_reports SET last_run_at = $2, next_run_at = $3, updated_at = NOW() WHERE id = $1
`

type UpdateScheduledReportRunTimesParams struct {
	ID        string           `json:"id"`
	LastRunAt pgtype.Timestamp `json:"last_run_at"`
	NextRunAt pgtype.Timestamp `json:"next_run_at"`
}

func (q *Queries) UpdateScheduledReportRunTimes(ctx context.Context, arg UpdateScheduledReportRunTimesParams) error {
	_, err := q.db.Exec(ctx, updateScheduledReportRunTimes, arg.ID, arg.LastRunAt, arg.NextRunAt)
	return err
}
