// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patch_schedules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePatchScheduleSlot = `-- name: ConsumePatchScheduleSlot :one
UPDATE patch_schedules
SET last_run_at = $1,
    enabled = CASE WHEN schedule_type = 'once' THEN false ELSE enabled END
WHERE id = $2
  AND enabled = true
  AND (last_run_at IS NULL OR last_run_at < $3)
RETURNING id
`

type ConsumePatchScheduleSlotParams struct {
	LastRunAt pgtype.Timestamp `json:"last_run_at"`
	ID        string           `json:"id"`
	Slot      pgtype.Timestamp `json:"slot"`
}

// Atomically claims a schedule slot (compare-and-set on last_run_at) so that
// concurrent dispatchers cannot run the same slot twice. Returns no row when
// the slot was already consumed. One-shot schedules are disabled in the same
// statement so a claim can never leave them armed.
// updated_at is intentionally left alone: it tracks config changes and the
// dispatcher skips slots older than it (no instant fire on create/enable).
func (q *Queries) ConsumePatchScheduleSlot(ctx context.Context, arg ConsumePatchScheduleSlotParams) (string, error) {
	row := q.db.QueryRow(ctx, consumePatchScheduleSlot, arg.LastRunAt, arg.ID, arg.Slot)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createPatchSchedule = `-- name: CreatePatchSchedule :one
INSERT INTO patch_schedules (
    id, name, host_group_id, schedule_type, run_at, weekday, time_of_day,
    timezone, enabled, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, NOW(), NOW()
) RETURNING id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, enabled, last_run_at, missed_at, created_by, created_at, updated_at
`

type CreatePatchScheduleParams struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	HostGroupID  string           `json:"host_group_id"`
	ScheduleType string           `json:"schedule_type"`
	RunAt        pgtype.Timestamp `json:"run_at"`
	Weekday      *int32           `json:"weekday"`
	TimeOfDay    *string          `json:"time_of_day"`
	Timezone     string           `json:"timezone"`
	Enabled      bool             `json:"enabled"`
	CreatedBy    *string          `json:"created_by"`
}

func (q *Queries) CreatePatchSchedule(ctx context.Context, arg CreatePatchScheduleParams) (PatchSchedule, error) {
	row := q.db.QueryRow(ctx, createPatchSchedule,
		arg.ID,
		arg.Name,
		arg.HostGroupID,
		arg.ScheduleType,
		arg.RunAt,
		arg.Weekday,
		arg.TimeOfDay,
		arg.Timezone,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i PatchSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostGroupID,
		&i.ScheduleType,
		&i.RunAt,
		&i.Weekday,
		&i.TimeOfDay,
		&i.Timezone,
		&i.Enabled,
		&i.LastRunAt,
		&i.MissedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatchSchedule = `-- name: DeletePatchSchedule :exec
DELETE FROM patch_schedules WHERE id = $1
`

func (q *Queries) DeletePatchSchedule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePatchSchedule, id)
	return err
}

const getPatchScheduleByID = `-- name: GetPatchScheduleByID :one
SELECT id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, enabled, last_run_at, missed_at, created_by, created_at, updated_at FROM patch_schedules WHERE id = $1
`

func (q *Queries) GetPatchScheduleByID(ctx context.Context, id string) (PatchSchedule, error) {
	row := q.db.QueryRow(ctx, getPatchScheduleByID, id)
	var i PatchSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostGroupID,
		&i.ScheduleType,
		&i.RunAt,
		&i.Weekday,
		&i.TimeOfDay,
		&i.Timezone,
		&i.Enabled,
		&i.LastRunAt,
		&i.MissedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledPatchSchedules = `-- name: ListEnabledPatchSchedules :many
SELECT id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, enabled, last_run_at, missed_at, created_by, created_at, updated_at FROM patch_schedules WHERE enabled = true ORDER BY id
`

func (q *Queries) ListEnabledPatchSchedules(ctx context.Context) ([]PatchSchedule, error) {
	rows, err := q.db.Query(ctx, listEnabledPatchSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatchSchedule
	for rows.Next() {
		var i PatchSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HostGroupID,
			&i.ScheduleType,
			&i.RunAt,
			&i.Weekday,
			&i.TimeOfDay,
			&i.Timezone,
			&i.Enabled,
			&i.LastRunAt,
			&i.MissedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchScheduleGroupHosts = `-- name: ListPatchScheduleGroupHosts :many
SELECT h.id, h.api_id, h.friendly_name, h.hostname
FROM host_group_memberships hgm
JOIN hosts h ON h.id = hgm.host_id
WHERE hgm.host_group_id = $1
ORDER BY h.friendly_name
`

type ListPatchScheduleGroupHostsRow struct {
	ID           string  `json:"id"`
	ApiID        string  `json:"api_id"`
	FriendlyName string  `json:"friendly_name"`
	Hostname     *string `json:"hostname"`
}

func (q *Queries) ListPatchScheduleGroupHosts(ctx context.Context, hostGroupID string) ([]ListPatchScheduleGroupHostsRow, error) {
	rows, err := q.db.Query(ctx, listPatchScheduleGroupHosts, hostGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchScheduleGroupHostsRow
	for rows.Next() {
		var i ListPatchScheduleGroupHostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiID,
			&i.FriendlyName,
			&i.Hostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchSchedules = `-- name: ListPatchSchedules :many
SELECT ps.id, ps.name, ps.host_group_id, ps.schedule_type, ps.run_at, ps.weekday, ps.time_of_day, ps.timezone, ps.enabled, ps.last_run_at, ps.missed_at, ps.created_by, ps.created_at, ps.updated_at, hg.name AS host_group_name
FROM patch_schedules ps
JOIN host_groups hg ON hg.id = ps.host_group_id
ORDER BY ps.name
`

type ListPatchSchedulesRow struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	HostGroupID   string           `json:"host_group_id"`
	ScheduleType  string           `json:"schedule_type"`
	RunAt         pgtype.Timestamp `json:"run_at"`
	Weekday       *int32           `json:"weekday"`
	TimeOfDay     *string          `json:"time_of_day"`
	Timezone      string           `json:"timezone"`
	Enabled       bool             `json:"enabled"`
	LastRunAt     pgtype.Timestamp `json:"last_run_at"`
	MissedAt      pgtype.Timestamp `json:"missed_at"`
	CreatedBy     *string          `json:"created_by"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	HostGroupName string           `json:"host_group_name"`
}

func (q *Queries) ListPatchSchedules(ctx context.Context) ([]ListPatchSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listPatchSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchSchedulesRow
	for rows.Next() {
		var i ListPatchSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HostGroupID,
			&i.ScheduleType,
			&i.RunAt,
			&i.Weekday,
			&i.TimeOfDay,
			&i.Timezone,
			&i.Enabled,
			&i.LastRunAt,
			&i.MissedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPatchScheduleMissed = `-- name: MarkPatchScheduleMissed :exec
UPDATE patch_schedules SET enabled = false, missed_at = $1, updated_at = NOW()
WHERE id = $2
`

type MarkPatchScheduleMissedParams struct {
	MissedAt pgtype.Timestamp `json:"missed_at"`
	ID       string           `json:"id"`
}

func (q *Queries) MarkPatchScheduleMissed(ctx context.Context, arg MarkPatchScheduleMissedParams) error {
	_, err := q.db.Exec(ctx, markPatchScheduleMissed, arg.MissedAt, arg.ID)
	return err
}

const setPatchScheduleEnabled = `-- name: SetPatchScheduleEnabled :one
UPDATE patch_schedules SET enabled = $1, missed_at = NULL, updated_at = NOW()
WHERE id = $2
RETURNING id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, enabled, last_run_at, missed_at, created_by, created_at, updated_at
`

type SetPatchScheduleEnabledParams struct {
	Enabled bool   `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) SetPatchScheduleEnabled(ctx context.Context, arg SetPatchScheduleEnabledParams) (PatchSchedule, error) {
	row := q.db.QueryRow(ctx, setPatchScheduleEnabled, arg.Enabled, arg.ID)
	var i PatchSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostGroupID,
		&i.ScheduleType,
		&i.RunAt,
		&i.Weekday,
		&i.TimeOfDay,
		&i.Timezone,
		&i.Enabled,
		&i.LastRunAt,
		&i.MissedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePatchSchedule = `-- name: UpdatePatchSchedule :one
UPDATE patch_schedules SET
    name = $1,
    host_group_id = $2,
    schedule_type = $3,
    run_at = $4,
    weekday = $5,
    time_of_day = $6,
    timezone = $7,
    enabled = $8,
    missed_at = $9,
    updated_at = NOW()
WHERE id = $10
RETURNING id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, enabled, last_run_at, missed_at, created_by, created_at, updated_at
`

type UpdatePatchScheduleParams struct {
	Name         string           `json:"name"`
	HostGroupID  string           `json:"host_group_id"`
	ScheduleType string           `json:"schedule_type"`
	RunAt        pgtype.Timestamp `json:"run_at"`
	Weekday      *int32           `json:"weekday"`
	TimeOfDay    *string          `json:"time_of_day"`
	Timezone     string           `json:"timezone"`
	Enabled      bool             `json:"enabled"`
	MissedAt     pgtype.Timestamp `json:"missed_at"`
	ID           string           `json:"id"`
}

func (q *Queries) UpdatePatchSchedule(ctx context.Context, arg UpdatePatchScheduleParams) (PatchSchedule, error) {
	row := q.db.QueryRow(ctx, updatePatchSchedule,
		arg.Name,
		arg.HostGroupID,
		arg.ScheduleType,
		arg.RunAt,
		arg.Weekday,
		arg.TimeOfDay,
		arg.Timezone,
		arg.Enabled,
		arg.MissedAt,
		arg.ID,
	)
	var i PatchSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostGroupID,
		&i.ScheduleType,
		&i.RunAt,
		&i.Weekday,
		&i.TimeOfDay,
		&i.Timezone,
		&i.Enabled,
		&i.LastRunAt,
		&i.MissedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userCanManagePatching = `-- name: UserCanManagePatching :one
SELECT u.is_active AND rp.can_manage_patching AS allowed
FROM users u
JOIN role_permissions rp ON rp.role = u.role
WHERE u.id = $1
`

// Execution-time revalidation of the schedule creator: the schedule must stop
// firing once its creator is deleted, deactivated or loses can_manage_patching.
func (q *Queries) UserCanManagePatching(ctx context.Context, id string) (*bool, error) {
	row := q.db.QueryRow(ctx, userCanManagePatching, id)
	var allowed *bool
	err := row.Scan(&allowed)
	return allowed, err
}
