// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"
)

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, role string) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, role)
	return err
}

const getRolePermissions = `-- name: GetRolePermissions :one
SELECT id, role, can_view_dashboard, can_view_hosts, can_manage_hosts, can_view_packages, can_manage_packages, can_view_users, can_manage_users, can_manage_superusers, can_view_reports, can_export_data, can_manage_settings, can_manage_notifications, can_view_notification_logs, can_manage_patching, can_manage_compliance, can_manage_docker, can_manage_alerts, can_manage_automation, can_use_remote_access, can_manage_billing, can_reboot_hosts, created_at, updated_at FROM role_permissions WHERE role = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, role string) (RolePermission, error) {
	row := q.db.QueryRow(ctx, getRolePermissions, role)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CanViewDashboard,
		&i.CanViewHosts,
		&i.CanManageHosts,
		&i.CanViewPackages,
		&i.CanManagePackages,
		&i.CanViewUsers,
		&i.CanManageUsers,
		&i.CanManageSuperusers,
		&i.CanViewReports,
		&i.CanExportData,
		&i.CanManageSettings,
		&i.CanManageNotifications,
		&i.CanViewNotificationLogs,
		&i.CanManagePatching,
		&i.CanManageCompliance,
		&i.CanManageDocker,
		&i.CanManageAlerts,
		&i.CanManageAutomation,
		&i.CanUseRemoteAccess,
		&i.CanManageBilling,
		&i.CanRebootHosts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, role, can_view_dashboard, can_view_hosts, can_manage_hosts, can_view_packages, can_manage_packages, can_view_users, can_manage_users, can_manage_superusers, can_view_reports, can_export_data, can_manage_settings, can_manage_notifications, can_view_notification_logs, can_manage_patching, can_manage_compliance, can_manage_docker, can_manage_alerts, can_manage_automation, can_use_remote_access, can_manage_billing, can_reboot_hosts, created_at, updated_at FROM role_permissions ORDER BY role
`

func (q *Queries) ListRoles(ctx context.Context) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.CanViewDashboard,
			&i.CanViewHosts,
			&i.CanManageHosts,
			&i.CanViewPackages,
			&i.CanManagePackages,
			&i.CanViewUsers,
			&i.CanManageUsers,
			&i.CanManageSuperusers,
			&i.CanViewReports,
			&i.CanExportData,
			&i.CanManageSettings,
			&i.CanManageNotifications,
			&i.CanViewNotificationLogs,
			&i.CanManagePatching,
			&i.CanManageCompliance,
			&i.CanManageDocker,
			&i.CanManageAlerts,
			&i.CanManageAutomation,
			&i.CanUseRemoteAccess,
			&i.CanManageBilling,
			&i.CanRebootHosts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRolePermissions = `-- name: UpsertRolePermissions :one
INSERT INTO role_permissions (
    id, role, can_view_dashboard, can_view_hosts, can_manage_hosts,
    can_view_packages, can_manage_packages, can_view_users, can_manage_users,
    can_manage_superusers, can_view_reports, can_export_data, can_manage_settings,
    can_manage_notifications, can_view_notification_logs,
    can_manage_patching, can_manage_compliance, can_manage_docker,
    can_manage_alerts, can_manage_automation, can_use_remote_access,
    can_manage_billing, can_reboot_hosts,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21, $22, $23,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
ON CONFLICT (role) DO UPDATE SET
    can_view_dashboard = EXCLUDED.can_view_dashboard,
    can_view_hosts = EXCLUDED.can_view_hosts,
    can_manage_hosts = EXCLUDED.can_manage_hosts,
    can_view_packages = EXCLUDED.can_view_packages,
    can_manage_packages = EXCLUDED.can_manage_packages,
    can_view_users = EXCLUDED.can_view_users,
    can_manage_users = EXCLUDED.can_manage_users,
    can_manage_superusers = EXCLUDED.can_manage_superusers,
    can_view_reports = EXCLUDED.can_view_reports,
    can_export_data = EXCLUDED.can_export_data,
    can_manage_settings = EXCLUDED.can_manage_settings,
    can_manage_notifications = EXCLUDED.can_manage_notifications,
    can_view_notification_logs = EXCLUDED.can_view_notification_logs,
    can_manage_patching = EXCLUDED.can_manage_patching,
    can_manage_compliance = EXCLUDED.can_manage_compliance,
    can_manage_docker = EXCLUDED.can_manage_docker,
    can_manage_alerts = EXCLUDED.can_manage_alerts,
    can_manage_automation = EXCLUDED.can_manage_automation,
    can_use_remote_access = EXCLUDED.can_use_remote_access,
    can_manage_billing = EXCLUDED.can_manage_billing,
    can_reboot_hosts = EXCLUDED.can_reboot_hosts,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, role, can_view_dashboard, can_view_hosts, can_manage_hosts, can_view_packages, can_manage_packages, can_view_users, can_manage_users, can_manage_superusers, can_view_reports, can_export_data, can_manage_settings, can_manage_notifications, can_view_notification_logs, can_manage_patching, can_manage_compliance, can_manage_docker, can_manage_alerts, can_manage_automation, can_use_remote_access, can_manage_billing, can_reboot_hosts, created_at, updated_at
`

type UpsertRolePermissionsParams struct {
	ID                      string `json:"id"`
	Role                    string `json:"role"`
	CanViewDashboard        bool   `json:"can_view_dashboard"`
	CanViewHosts            bool   `json:"can_view_hosts"`
	CanManageHosts          bool   `json:"can_manage_hosts"`
	CanViewPackages         bool   `json:"can_view_packages"`
	CanManagePackages       bool   `json:"can_manage_packages"`
	CanViewUsers            bool   `json:"can_view_users"`
	CanManageUsers          bool   `json:"can_manage_users"`
	CanManageSuperusers     bool   `json:"can_manage_superusers"`
	CanViewReports          bool   `json:"can_view_reports"`
	CanExportData           bool   `json:"can_export_data"`
	CanManageSettings       bool   `json:"can_manage_settings"`
	CanManageNotifications  bool   `json:"can_manage_notifications"`
	CanViewNotificationLogs bool   `json:"can_view_notification_logs"`
	CanManagePatching       bool   `json:"can_manage_patching"`
	CanManageCompliance     bool   `json:"can_manage_compliance"`
	CanManageDocker         bool   `json:"can_manage_docker"`
	CanManageAlerts         bool   `json:"can_manage_alerts"`
	CanManageAutomation     bool   `json:"can_manage_automation"`
	CanUseRemoteAccess      bool   `json:"can_use_remote_access"`
	CanManageBilling        bool   `json:"can_manage_billing"`
	CanRebootHosts          bool   `json:"can_reboot_hosts"`
}

func (q *Queries) UpsertRolePermissions(ctx context.Context, arg UpsertRolePermissionsParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, upsertRolePermissions,
		arg.ID,
		arg.Role,
		arg.CanViewDashboard,
		arg.CanViewHosts,
		arg.CanManageHosts,
		arg.CanViewPackages,
		arg.CanManagePackages,
		arg.CanViewUsers,
		arg.CanManageUsers,
		arg.CanManageSuperusers,
		arg.CanViewReports,
		arg.CanExportData,
		arg.CanManageSettings,
		arg.CanManageNotifications,
		arg.CanViewNotificationLogs,
		arg.CanManagePatching,
		arg.CanManageCompliance,
		arg.CanManageDocker,
		arg.CanManageAlerts,
		arg.CanManageAutomation,
		arg.CanUseRemoteAccess,
		arg.CanManageBilling,
		arg.CanRebootHosts,
	)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CanViewDashboard,
		&i.CanViewHosts,
		&i.CanManageHosts,
		&i.CanViewPackages,
		&i.CanManagePackages,
		&i.CanViewUsers,
		&i.CanManageUsers,
		&i.CanManageSuperusers,
		&i.CanViewReports,
		&i.CanExportData,
		&i.CanManageSettings,
		&i.CanManageNotifications,
		&i.CanViewNotificationLogs,
		&i.CanManagePatching,
		&i.CanManageCompliance,
		&i.CanManageDocker,
		&i.CanManageAlerts,
		&i.CanManageAutomation,
		&i.CanUseRemoteAccess,
		&i.CanManageBilling,
		&i.CanRebootHosts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
