// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reboot_schedules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRebootScheduleSlot = `-- name: ConsumeRebootScheduleSlot :one
UPDATE reboot_schedules
SET last_run_at = $1,
    enabled = CASE WHEN schedule_type = 'once' THEN false ELSE enabled END
WHERE id = $2
  AND enabled = true
  AND (last_run_at IS NULL OR last_run_at < $3)
RETURNING id
`

type ConsumeRebootScheduleSlotParams struct {
	LastRunAt pgtype.Timestamp `json:"last_run_at"`
	ID        string           `json:"id"`
	Slot      pgtype.Timestamp `json:"slot"`
}

// Atomically claims a schedule slot (compare-and-set on last_run_at) so that
// concurrent dispatchers cannot run the same slot twice. Returns no row when
// the slot was already consumed. One-shot schedules are disabled in the same
// statement so a claim can never leave them armed.
// updated_at is intentionally left alone: it tracks config changes and the
// dispatcher skips slots older than it (no instant fire on create/enable).
func (q *Queries) ConsumeRebootScheduleSlot(ctx context.Context, arg ConsumeRebootScheduleSlotParams) (string, error) {
	row := q.db.QueryRow(ctx, consumeRebootScheduleSlot, arg.LastRunAt, arg.ID, arg.Slot)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createRebootSchedule = `-- name: CreateRebootSchedule :one
INSERT INTO reboot_schedules (
    id, name, host_group_id, schedule_type, run_at, weekday, time_of_day,
    timezone, only_if_required, enabled, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, NOW(), NOW()
) RETURNING id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, only_if_required, enabled, last_run_at, missed_at, created_by, created_at, updated_at
`

type CreateRebootScheduleParams struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	HostGroupID    string           `json:"host_group_id"`
	ScheduleType   string           `json:"schedule_type"`
	RunAt          pgtype.Timestamp `json:"run_at"`
	Weekday        *int32           `json:"weekday"`
	TimeOfDay      *string          `json:"time_of_day"`
	Timezone       string           `json:"timezone"`
	OnlyIfRequired bool             `json:"only_if_required"`
	Enabled        bool             `json:"enabled"`
	CreatedBy      *string          `json:"created_by"`
}

func (q *Queries) CreateRebootSchedule(ctx context.Context, arg CreateRebootScheduleParams) (RebootSchedule, error) {
	row := q.db.QueryRow(ctx, createRebootSchedule,
		arg.ID,
		arg.Name,
		arg.HostGroupID,
		arg.ScheduleType,
		arg.RunAt,
		arg.Weekday,
		arg.TimeOfDay,
		arg.Timezone,
		arg.OnlyIfRequired,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i RebootSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostGroupID,
		&i.ScheduleType,
		&i.RunAt,
		&i.Weekday,
		&i.TimeOfDay,
		&i.Timezone,
		&i.OnlyIfRequired,
		&i.Enabled,
		&i.LastRunAt,
		&i.MissedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRebootSchedule = `-- name: DeleteRebootSchedule :exec
DELETE FROM reboot_schedules WHERE id = $1
`

func (q *Queries) DeleteRebootSchedule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRebootSchedule, id)
	return err
}

const getRebootScheduleByID = `-- name: GetRebootScheduleByID :one
SELECT id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, only_if_required, enabled, last_run_at, missed_at, created_by, created_at, updated_at FROM reboot_schedules WHERE id = $1
`

func (q *Queries) GetRebootScheduleByID(ctx context.Context, id string) (RebootSchedule, error) {
	row := q.db.QueryRow(ctx, getRebootScheduleByID, id)
	var i RebootSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostGroupID,
		&i.ScheduleType,
		&i.RunAt,
		&i.Weekday,
		&i.TimeOfDay,
		&i.Timezone,
		&i.OnlyIfRequired,
		&i.Enabled,
		&i.LastRunAt,
		&i.MissedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRebootSchedules = `-- name: ListEnabledRebootSchedules :many
SELECT id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, only_if_required, enabled, last_run_at, missed_at, created_by, created_at, updated_at FROM reboot_schedules WHERE enabled = true ORDER BY id
`

func (q *Queries) ListEnabledRebootSchedules(ctx context.Context) ([]RebootSchedule, error) {
	rows, err := q.db.Query(ctx, listEnabledRebootSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RebootSchedule
	for rows.Next() {
		var i RebootSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HostGroupID,
			&i.ScheduleType,
			&i.RunAt,
			&i.Weekday,
			&i.TimeOfDay,
			&i.Timezone,
			&i.OnlyIfRequired,
			&i.Enabled,
			&i.LastRunAt,
			&i.MissedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRebootScheduleGroupHosts = `-- name: ListRebootScheduleGroupHosts :many
SELECT h.id, h.api_id, h.friendly_name, h.hostname, h.machine_id, h.allow_reboot, h.needs_reboot
FROM host_group_memberships hgm
JOIN hosts h ON h.id = hgm.host_id
WHERE hgm.host_group_id = $1
ORDER BY h.friendly_name
`

type ListRebootScheduleGroupHostsRow struct {
	ID           string  `json:"id"`
	ApiID        string  `json:"api_id"`
	FriendlyName string  `json:"friendly_name"`
	Hostname     *string `json:"hostname"`
	MachineID    *string `json:"machine_id"`
	AllowReboot  bool    `json:"allow_reboot"`
	NeedsReboot  *bool   `json:"needs_reboot"`
}

func (q *Queries) ListRebootScheduleGroupHosts(ctx context.Context, hostGroupID string) ([]ListRebootScheduleGroupHostsRow, error) {
	rows, err := q.db.Query(ctx, listRebootScheduleGroupHosts, hostGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRebootScheduleGroupHostsRow
	for rows.Next() {
		var i ListRebootScheduleGroupHostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiID,
			&i.FriendlyName,
			&i.Hostname,
			&i.MachineID,
			&i.AllowReboot,
			&i.NeedsReboot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRebootSchedules = `-- name: ListRebootSchedules :many
SELECT rs.id, rs.name, rs.host_group_id, rs.schedule_type, rs.run_at, rs.weekday, rs.time_of_day, rs.timezone, rs.only_if_required, rs.enabled, rs.last_run_at, rs.missed_at, rs.created_by, rs.created_at, rs.updated_at, hg.name AS host_group_name
FROM reboot_schedules rs
JOIN host_groups hg ON hg.id = rs.host_group_id
ORDER BY rs.name
`

type ListRebootSchedulesRow struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	HostGroupID    string           `json:"host_group_id"`
	ScheduleType   string           `json:"schedule_type"`
	RunAt          pgtype.Timestamp `json:"run_at"`
	Weekday        *int32           `json:"weekday"`
	TimeOfDay      *string          `json:"time_of_day"`
	Timezone       string           `json:"timezone"`
	OnlyIfRequired bool             `json:"only_if_required"`
	Enabled        bool             `json:"enabled"`
	LastRunAt      pgtype.Timestamp `json:"last_run_at"`
	MissedAt       pgtype.Timestamp `json:"missed_at"`
	CreatedBy      *string          `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	HostGroupName  string           `json:"host_group_name"`
}

func (q *Queries) ListRebootSchedules(ctx context.Context) ([]ListRebootSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listRebootSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRebootSchedulesRow
	for rows.Next() {
		var i ListRebootSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HostGroupID,
			&i.ScheduleType,
			&i.RunAt,
			&i.Weekday,
			&i.TimeOfDay,
			&i.Timezone,
			&i.OnlyIfRequired,
			&i.Enabled,
			&i.LastRunAt,
			&i.MissedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRebootScheduleMissed = `-- name: MarkRebootScheduleMissed :exec
UPDATE reboot_schedules SET enabled = false, missed_at = $1, updated_at = NOW()
WHERE id = $2
`

type MarkRebootScheduleMissedParams struct {
	MissedAt pgtype.Timestamp `json:"missed_at"`
	ID       string           `json:"id"`
}

func (q *Queries) MarkRebootScheduleMissed(ctx context.Context, arg MarkRebootScheduleMissedParams) error {
	_, err := q.db.Exec(ctx, markRebootScheduleMissed, arg.MissedAt, arg.ID)
	return err
}

const setRebootScheduleEnabled = `-- name: SetRebootScheduleEnabled :one
UPDATE reboot_schedules SET enabled = $1, missed_at = NULL, updated_at = NOW()
WHERE id = $2
RETURNING id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, only_if_required, enabled, last_run_at, missed_at, created_by, created_at, updated_at
`

type SetRebootScheduleEnabledParams struct {
	Enabled bool   `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) SetRebootScheduleEnabled(ctx context.Context, arg SetRebootScheduleEnabledParams) (RebootSchedule, error) {
	row := q.db.QueryRow(ctx, setRebootScheduleEnabled, arg.Enabled, arg.ID)
	var i RebootSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostGroupID,
		&i.ScheduleType,
		&i.RunAt,
		&i.Weekday,
		&i.TimeOfDay,
		&i.Timezone,
		&i.OnlyIfRequired,
		&i.Enabled,
		&i.LastRunAt,
		&i.MissedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRebootSchedule = `-- name: UpdateRebootSchedule :one
UPDATE reboot_schedules SET
    name = $1,
    host_group_id = $2,
    schedule_type = $3,
    run_at = $4,
    weekday = $5,
    time_of_day = $6,
    timezone = $7,
    only_if_required = $8,
    enabled = $9,
    missed_at = $10,
    updated_at = NOW()
WHERE id = $11
RETURNING id, name, host_group_id, schedule_type, run_at, weekday, time_of_day, timezone, only_if_required, enabled, last_run_at, missed_at, created_by, created_at, updated_at
`

type UpdateRebootScheduleParams struct {
	Name           string           `json:"name"`
	HostGroupID    string           `json:"host_group_id"`
	ScheduleType   string           `json:"schedule_type"`
	RunAt          pgtype.Timestamp `json:"run_at"`
	Weekday        *int32           `json:"weekday"`
	TimeOfDay      *string          `json:"time_of_day"`
	Timezone       string           `json:"timezone"`
	OnlyIfRequired bool             `json:"only_if_required"`
	Enabled        bool             `json:"enabled"`
	MissedAt       pgtype.Timestamp `json:"missed_at"`
	ID             string           `json:"id"`
}

func (q *Queries) UpdateRebootSchedule(ctx context.Context, arg UpdateRebootScheduleParams) (RebootSchedule, error) {
	row := q.db.QueryRow(ctx, updateRebootSchedule,
		arg.Name,
		arg.HostGroupID,
		arg.ScheduleType,
		arg.RunAt,
		arg.Weekday,
		arg.TimeOfDay,
		arg.Timezone,
		arg.OnlyIfRequired,
		arg.Enabled,
		arg.MissedAt,
		arg.ID,
	)
	var i RebootSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostGroupID,
		&i.ScheduleType,
		&i.RunAt,
		&i.Weekday,
		&i.TimeOfDay,
		&i.Timezone,
		&i.OnlyIfRequired,
		&i.Enabled,
		&i.LastRunAt,
		&i.MissedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userCanRebootHosts = `-- name: UserCanRebootHosts :one
SELECT u.is_active AND rp.can_reboot_hosts AS allowed
FROM users u
JOIN role_permissions rp ON rp.role = u.role
WHERE u.id = $1
`

// Execution-time revalidation of the schedule creator: the schedule must stop
// firing once its creator is deleted, deactivated or loses can_reboot_hosts.
func (q *Queries) UserCanRebootHosts(ctx context.Context, id string) (*bool, error) {
	row := q.db.QueryRow(ctx, userCanRebootHosts, id)
	var allowed *bool
	err := row.Scan(&allowed)
	return allowed, err
}
