// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_statistics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSystemStatistics = `-- name: GetLatestSystemStatistics :one
SELECT total_packages, unique_packages_count, unique_security_count, timestamp
FROM system_statistics
ORDER BY timestamp DESC
LIMIT 1
`

type GetLatestSystemStatisticsRow struct {
	TotalPackages       int32            `json:"total_packages"`
	UniquePackagesCount int32            `json:"unique_packages_count"`
	UniqueSecurityCount int32            `json:"unique_security_count"`
	Timestamp           pgtype.Timestamp `json:"timestamp"`
}

func (q *Queries) GetLatestSystemStatistics(ctx context.Context) (GetLatestSystemStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getLatestSystemStatistics)
	var i GetLatestSystemStatisticsRow
	err := row.Scan(
		&i.TotalPackages,
		&i.UniquePackagesCount,
		&i.UniqueSecurityCount,
		&i.Timestamp,
	)
	return i, err
}

const getSystemStatisticsDaily = `-- name: GetSystemStatisticsDaily :many
SELECT DATE(timestamp)::text as ts,
    MAX(unique_packages_count)::int as packages_count,
    MAX(unique_security_count)::int as security_count,
    MAX(total_packages)::int as total_packages
FROM system_statistics
WHERE timestamp >= $1 AND timestamp <= $2
  AND total_packages >= 0
  AND unique_packages_count >= 0
  AND unique_security_count >= 0
  AND unique_security_count <= unique_packages_count
GROUP BY DATE(timestamp)
ORDER BY ts
`

type GetSystemStatisticsDailyParams struct {
	Timestamp   pgtype.Timestamp `json:"timestamp"`
	Timestamp_2 pgtype.Timestamp `json:"timestamp_2"`
}

type GetSystemStatisticsDailyRow struct {
	Ts            string `json:"ts"`
	PackagesCount int32  `json:"packages_count"`
	SecurityCount int32  `json:"security_count"`
	TotalPackages int32  `json:"total_packages"`
}

func (q *Queries) GetSystemStatisticsDaily(ctx context.Context, arg GetSystemStatisticsDailyParams) ([]GetSystemStatisticsDailyRow, error) {
	rows, err := q.db.Query(ctx, getSystemStatisticsDaily, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSystemStatisticsDailyRow
	for rows.Next() {
		var i GetSystemStatisticsDailyRow
		if err := rows.Scan(
			&i.Ts,
			&i.PackagesCount,
			&i.SecurityCount,
			&i.TotalPackages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemStatsForInsert = `-- name: GetSystemStatsForInsert :one
SELECT
    (SELECT COUNT(DISTINCT p.id)::int FROM packages p
        INNER JOIN host_packages hp ON hp.package_id = p.id AND hp.needs_update = true
            AND NOT ($1::boolean AND fork_is_definition_update(hp.wua_categories, hp.wua_kb))),
    (SELECT COUNT(DISTINCT p.id)::int FROM packages p
        INNER JOIN host_packages hp ON hp.package_id = p.id AND hp.needs_update = true AND hp.is_security_update = true
            AND NOT ($1::boolean AND fork_is_definition_update(hp.wua_categories, hp.wua_kb))),
    (SELECT COUNT(DISTINCT p.id)::int FROM packages p
        WHERE EXISTS (SELECT 1 FROM host_packages hp WHERE hp.package_id = p.id)),
    (SELECT COUNT(*)::int FROM hosts WHERE status = 'active'),
    (SELECT COUNT(DISTINCT h.id)::int FROM hosts h
        INNER JOIN host_packages hp ON hp.host_id = h.id AND hp.needs_update = true
            AND NOT ($1::boolean AND fork_is_definition_update(hp.wua_categories, hp.wua_kb)))
`

type GetSystemStatsForInsertRow struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int32 `json:"column_3"`
	Column4 int32 `json:"column_4"`
	Column5 int32 `json:"column_5"`
}

// fork: PM_IGNORE_DEFINITION_UPDATES (the three needs_update subselects exclude Definition Updates when the flag is on; total packages/total hosts are untouched)
func (q *Queries) GetSystemStatsForInsert(ctx context.Context, ignoreDefinitionUpdates bool) (GetSystemStatsForInsertRow, error) {
	row := q.db.QueryRow(ctx, getSystemStatsForInsert, ignoreDefinitionUpdates)
	var i GetSystemStatsForInsertRow
	err := row.Scan(
		&i.Column1,
		&i.Column2,
		&i.Column3,
		&i.Column4,
		&i.Column5,
	)
	return i, err
}

const insertSystemStatistics = `-- name: InsertSystemStatistics :exec
INSERT INTO system_statistics (id, unique_packages_count, unique_security_count, total_packages, total_hosts, hosts_needing_updates, timestamp)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
`

type InsertSystemStatisticsParams struct {
	ID                  string `json:"id"`
	UniquePackagesCount int32  `json:"unique_packages_count"`
	UniqueSecurityCount int32  `json:"unique_security_count"`
	TotalPackages       int32  `json:"total_packages"`
	TotalHosts          int32  `json:"total_hosts"`
	HostsNeedingUpdates int32  `json:"hosts_needing_updates"`
}

func (q *Queries) InsertSystemStatistics(ctx context.Context, arg InsertSystemStatisticsParams) error {
	_, err := q.db.Exec(ctx, insertSystemStatistics,
		arg.ID,
		arg.UniquePackagesCount,
		arg.UniqueSecurityCount,
		arg.TotalPackages,
		arg.TotalHosts,
		arg.HostsNeedingUpdates,
	)
	return err
}

const listSystemStatisticsByDateRange = `-- name: ListSystemStatisticsByDateRange :many
SELECT id, unique_packages_count, unique_security_count, total_packages, total_hosts, hosts_needing_updates, timestamp
FROM system_statistics
WHERE timestamp >= $1 AND timestamp <= $2
ORDER BY timestamp ASC
`

type ListSystemStatisticsByDateRangeParams struct {
	Timestamp   pgtype.Timestamp `json:"timestamp"`
	Timestamp_2 pgtype.Timestamp `json:"timestamp_2"`
}

func (q *Queries) ListSystemStatisticsByDateRange(ctx context.Context, arg ListSystemStatisticsByDateRangeParams) ([]SystemStatistic, error) {
	rows, err := q.db.Query(ctx, listSystemStatisticsByDateRange, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemStatistic
	for rows.Next() {
		var i SystemStatistic
		if err := rows.Scan(
			&i.ID,
			&i.UniquePackagesCount,
			&i.UniqueSecurityCount,
			&i.TotalPackages,
			&i.TotalHosts,
			&i.HostsNeedingUpdates,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
