// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: windows_updates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWindowsUpdatesByHostID = `-- name: CountWindowsUpdatesByHostID :one
SELECT
    COUNT(*) FILTER (WHERE needs_update = true)::int                          AS pending_count,
    COUNT(*) FILTER (WHERE needs_update = true AND is_security_update = true)::int AS security_count,
    COUNT(*) FILTER (WHERE needs_update = false)::int                         AS installed_count
FROM host_packages
WHERE host_id = $1 AND wua_guid IS NOT NULL
`

type CountWindowsUpdatesByHostIDRow struct {
	PendingCount   int32 `json:"pending_count"`
	SecurityCount  int32 `json:"security_count"`
	InstalledCount int32 `json:"installed_count"`
}

// Counts pending Windows Updates for a host (for dashboard/stats).
func (q *Queries) CountWindowsUpdatesByHostID(ctx context.Context, hostID string) (CountWindowsUpdatesByHostIDRow, error) {
	row := q.db.QueryRow(ctx, countWindowsUpdatesByHostID, hostID)
	var i CountWindowsUpdatesByHostIDRow
	err := row.Scan(&i.PendingCount, &i.SecurityCount, &i.InstalledCount)
	return i, err
}

const deleteHostPackageByWUAGUID = `-- name: DeleteHostPackageByWUAGUID :exec
DELETE FROM host_packages WHERE host_id = $1 AND wua_guid = $2
`

type DeleteHostPackageByWUAGUIDParams struct {
	HostID  string  `json:"host_id"`
	WuaGuid *string `json:"wua_guid"`
}

// Removes a host_package row that was reported as superseded by the agent.
func (q *Queries) DeleteHostPackageByWUAGUID(ctx context.Context, arg DeleteHostPackageByWUAGUIDParams) error {
	_, err := q.db.Exec(ctx, deleteHostPackageByWUAGUID, arg.HostID, arg.WuaGuid)
	return err
}

const deleteHostPackagesByWUAGUIDs = `-- name: DeleteHostPackagesByWUAGUIDs :exec
DELETE FROM host_packages WHERE host_id = $1 AND wua_guid = ANY($2::text[])
`

type DeleteHostPackagesByWUAGUIDsParams struct {
	HostID  string   `json:"host_id"`
	Column2 []string `json:"column_2"`
}

// Bulk-removes superseded Windows Update entries for a host.
func (q *Queries) DeleteHostPackagesByWUAGUIDs(ctx context.Context, arg DeleteHostPackagesByWUAGUIDsParams) error {
	_, err := q.db.Exec(ctx, deleteHostPackagesByWUAGUIDs, arg.HostID, arg.Column2)
	return err
}

const getHostWindowsUpdates = `-- name: GetHostWindowsUpdates :many

SELECT hp.id, hp.host_id, hp.package_id, hp.current_version, hp.available_version,
    hp.needs_update, hp.is_security_update,
    hp.wua_guid, hp.wua_kb, hp.wua_severity, hp.wua_categories,
    hp.wua_description, hp.wua_support_url, hp.wua_revision_number,
    hp.wua_date_installed, hp.wua_install_result, hp.last_checked,
    p.name AS pkg_name, p.description AS pkg_description
FROM host_packages hp
JOIN packages p ON p.id = hp.package_id
WHERE hp.host_id = $1
  AND hp.wua_guid IS NOT NULL
ORDER BY hp.needs_update DESC, hp.is_security_update DESC, p.name ASC
`

type GetHostWindowsUpdatesRow struct {
	ID                string           `json:"id"`
	HostID            string           `json:"host_id"`
	PackageID         string           `json:"package_id"`
	CurrentVersion    string           `json:"current_version"`
	AvailableVersion  *string          `json:"available_version"`
	NeedsUpdate       bool             `json:"needs_update"`
	IsSecurityUpdate  bool             `json:"is_security_update"`
	WuaGuid           *string          `json:"wua_guid"`
	WuaKb             *string          `json:"wua_kb"`
	WuaSeverity       *string          `json:"wua_severity"`
	WuaCategories     []byte           `json:"wua_categories"`
	WuaDescription    *string          `json:"wua_description"`
	WuaSupportUrl     *string          `json:"wua_support_url"`
	WuaRevisionNumber *int32           `json:"wua_revision_number"`
	WuaDateInstalled  pgtype.Timestamp `json:"wua_date_installed"`
	WuaInstallResult  *string          `json:"wua_install_result"`
	LastChecked       pgtype.Timestamp `json:"last_checked"`
	PkgName           string           `json:"pkg_name"`
	PkgDescription    *string          `json:"pkg_description"`
}

// Windows Update (WUA) specific queries
// These operate on host_packages rows where category='Windows Update' and wua_guid IS NOT NULL
// Returns all Windows Update entries for a host, most recently checked first.
func (q *Queries) GetHostWindowsUpdates(ctx context.Context, hostID string) ([]GetHostWindowsUpdatesRow, error) {
	rows, err := q.db.Query(ctx, getHostWindowsUpdates, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostWindowsUpdatesRow
	for rows.Next() {
		var i GetHostWindowsUpdatesRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackageID,
			&i.CurrentVersion,
			&i.AvailableVersion,
			&i.NeedsUpdate,
			&i.IsSecurityUpdate,
			&i.WuaGuid,
			&i.WuaKb,
			&i.WuaSeverity,
			&i.WuaCategories,
			&i.WuaDescription,
			&i.WuaSupportUrl,
			&i.WuaRevisionNumber,
			&i.WuaDateInstalled,
			&i.WuaInstallResult,
			&i.LastChecked,
			&i.PkgName,
			&i.PkgDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingWindowsUpdateGUIDs = `-- name: GetPendingWindowsUpdateGUIDs :many
SELECT wua_guid FROM host_packages
WHERE host_id = $1
  AND wua_guid IS NOT NULL
  AND needs_update = true
  AND (wua_install_result IS NULL OR wua_install_result = 'failed')
ORDER BY is_security_update DESC, last_checked ASC
`

// Returns WUA GUIDs that are still pending (needs_update=true, not yet installed) for a host.
// Used by the server to tell the agent which updates to install.
func (q *Queries) GetPendingWindowsUpdateGUIDs(ctx context.Context, hostID string) ([]*string, error) {
	rows, err := q.db.Query(ctx, getPendingWindowsUpdateGUIDs, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var wua_guid *string
		if err := rows.Scan(&wua_guid); err != nil {
			return nil, err
		}
		items = append(items, wua_guid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWUAGuidsByPackageNames = `-- name: GetWUAGuidsByPackageNames :many
SELECT p.name, hp.wua_guid
FROM host_packages hp
JOIN packages p ON p.id = hp.package_id
WHERE hp.host_id = $1
  AND p.name = ANY($2::text[])
  AND hp.wua_guid IS NOT NULL
`

type GetWUAGuidsByPackageNamesParams struct {
	HostID string   `json:"host_id"`
	Names  []string `json:"names"`
}

type GetWUAGuidsByPackageNamesRow struct {
	Name    string  `json:"name"`
	WuaGuid *string `json:"wua_guid"`
}

// Resolves package (update) names to their WUA GUIDs for one host. Used when
// dispatching per-package patch runs to Windows agents, which install by GUID.
func (q *Queries) GetWUAGuidsByPackageNames(ctx context.Context, arg GetWUAGuidsByPackageNamesParams) ([]GetWUAGuidsByPackageNamesRow, error) {
	rows, err := q.db.Query(ctx, getWUAGuidsByPackageNames, arg.HostID, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWUAGuidsByPackageNamesRow
	for rows.Next() {
		var i GetWUAGuidsByPackageNamesRow
		if err := rows.Scan(&i.Name, &i.WuaGuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHostPackageWUAInstallResult = `-- name: UpdateHostPackageWUAInstallResult :exec
UPDATE host_packages SET
    wua_install_result = $3,
    wua_date_installed = CASE WHEN $3 = 'success' THEN NOW() ELSE wua_date_installed END,
    needs_update       = CASE WHEN $3 = 'success' THEN false ELSE needs_update END,
    current_version    = CASE WHEN $3 = 'success' THEN COALESCE(available_version, current_version) ELSE current_version END,
    last_checked       = NOW()
WHERE host_id = $1 AND wua_guid = $2
`

type UpdateHostPackageWUAInstallResultParams struct {
	HostID           string  `json:"host_id"`
	WuaGuid          *string `json:"wua_guid"`
	WuaInstallResult *string `json:"wua_install_result"`
}

// Records the outcome of a Windows Update installation for a specific host+GUID combination.
func (q *Queries) UpdateHostPackageWUAInstallResult(ctx context.Context, arg UpdateHostPackageWUAInstallResultParams) error {
	_, err := q.db.Exec(ctx, updateHostPackageWUAInstallResult, arg.HostID, arg.WuaGuid, arg.WuaInstallResult)
	return err
}
